//! The diagram: an ordered set of shapes, drawable into a buffer the caller gives it. See
//! [`docs/diagram-model.md`](../../../docs/diagram-model.md) and
//! [ADR-0042](../../../docs/decisions/0042-draw-a-diagram-front-to-back-into-a-given-window.md).

use std::fmt;

use monospace_core::{Buffer, Layer, StampMode};

use crate::Shape;

/// A shape's identity: normally generated by the diagram that placed it and unique within it
/// (FR-001, FR-002), though [`ShapeId::new`] can also build one directly from its text.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ShapeId(String);

impl ShapeId {
    /// Builds an identity directly from its text — `"#1"`, `"#2"`, and so on.
    pub fn new(text: impl Into<String>) -> Self {
        Self(text.into())
    }
}

impl fmt::Display for ShapeId {
    /// Writes the identity as `#1`, `#2`, and so on.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

/// One entry of a diagram's order: a shape and the identity the diagram gave it.
struct Placed {
    id: ShapeId,
    shape: Shape,
}

/// A diagram: an ordered set of shapes, and nothing else — no buffer, no glyph catalog, no
/// rendered picture (FR-005).
#[derive(Default)]
pub struct Diagram {
    /// The order the shapes draw in. The **last** element is the front of the order (research.md
    /// Q2): it is drawn first and decides a shared cell before anything behind it.
    shapes: Vec<Placed>,
    /// The ordinal the next `add` numbers its identity with.
    next: u32,
}

impl Diagram {
    /// An empty diagram, holding no shapes.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Puts `shape` at the front of the order, in front of everything already there, and returns
    /// the identity the diagram gave it (FR-002, FR-006).
    pub fn add(&mut self, shape: Shape) -> ShapeId {
        self.next += 1;
        let id = ShapeId(format!("#{}", self.next));
        self.shapes.push(Placed {
            id: id.clone(),
            shape,
        });
        id
    }

    /// The place in the order the shape named by `id` stands, or `None` when this diagram holds
    /// no such shape.
    ///
    /// The one search every method naming a shape by its identity goes through. `ShapeId`s are
    /// compared by value, so an identity issued by another diagram is a well-formed value that
    /// matches nothing here — the same answer the model's _Positions_ gives a reference to a shape
    /// that is not there.
    fn find(&self, id: &ShapeId) -> Option<usize> {
        self.shapes.iter().position(|placed| &placed.id == id)
    }

    /// Moves the shape named by `id` one place toward the front of the order. Does nothing when
    /// `id` names no shape here, or when it is already the front-most (FR-007, FR-009, FR-010,
    /// FR-011).
    pub fn forward(&mut self, id: &ShapeId) {
        if let Some(index) = self.find(id)
            && index + 1 < self.shapes.len()
        {
            self.shapes.swap(index, index + 1);
        }
    }

    /// Moves the shape named by `id` one place toward the back of the order. Does nothing when
    /// `id` names no shape here, or when it is already the back-most (FR-008, FR-009, FR-010,
    /// FR-011).
    pub fn backward(&mut self, id: &ShapeId) {
        if let Some(index) = self.find(id)
            && index > 0
        {
            self.shapes.swap(index, index - 1);
        }
    }

    /// The figure named by `id`, or `None` when this diagram holds no such shape.
    ///
    /// The crate's first reader, and the only one: one query by an identity the caller already
    /// holds, and nothing coming back the other way. There is no listing of a diagram's
    /// identities, no count, no order, and no way to ask which shape decided a position.
    ///
    /// It borrows, and there is no `cloned()` beside it. What comes back is the bare figure the
    /// caller added, with the identity and the place in the order held here in the diagram rather
    /// than inside the figure, so nothing about what is returned says where it sits.
    #[must_use]
    pub fn get(&self, id: &ShapeId) -> Option<&Shape> {
        self.find(id).map(|index| &self.shapes[index].shape)
    }

    /// Takes the shape named by `id` out of the diagram, changing nothing else.
    ///
    /// An identity this diagram does not hold changes nothing, with no error, no report and no
    /// panic, which is the same answer the model's _Positions_ gives a reference to a shape that
    /// is not there. The gap is closed, so what remains of the order keeps the order it had: a
    /// removal changes the holding and nothing else.
    ///
    /// It hands back nothing. There is no history and nothing to undo, so putting a figure back
    /// means building it again. The counter is not touched either, so an identity is never handed
    /// out a second time.
    pub fn remove(&mut self, id: &ShapeId) {
        if let Some(index) = self.find(id) {
            self.shapes.remove(index);
        }
    }

    /// Puts `shape` where the shape named by `id` stands, in the same place in the order.
    ///
    /// The identity and the place in the order survive, and everything the previous figure owned
    /// is the new figure's: its kind, its parameters and its position. The diagram never reaches
    /// into a box and widens it, and a replacement may change the kind outright, a box becoming a
    /// line, with nothing of the previous figure surviving it.
    ///
    /// An identity this diagram does not hold changes nothing, and the shape handed in is not
    /// added either, so there is no way to name a shape into existence. It takes the shape by
    /// value and hands back nothing, for the reason [`Diagram::remove`] does.
    pub fn replace(&mut self, id: &ShapeId, shape: Shape) {
        if let Some(index) = self.find(id) {
            self.shapes[index].shape = shape;
        }
    }

    /// Draws every shape into `buffer`, front to back, stamping every cell with
    /// [`StampMode::Below`] (FR-010 to FR-012). Drawing changes nothing about this diagram
    /// (FR-015), so two drawings into equal windows produce equal buffers.
    pub fn draw(&self, buffer: &mut Buffer) {
        let mut layer = Layer::new(buffer, StampMode::Below);
        for placed in self.shapes.iter().rev() {
            placed.shape.draw(&mut layer);
        }
    }
}

#[cfg(test)]
mod tests {
    use monospace_core::{
        BoxShape, Buffer, Cell, Connector, Direction, Glyph, GlyphCatalog, Layer, Line,
        Orientation, Pos, Shape as CoreShape, Size, StampMode, Stroke, Terminal, render,
    };

    use super::{Diagram, ShapeId};
    use crate::{Delta, Endpoint, Shape};

    fn light() -> Stroke {
        Stroke::from("light")
    }

    /// Collects every cell of `buffer` over the window `origin`/`size`, so two buffers can be
    /// compared by value even though `Buffer` derives no `PartialEq` (research.md Q7).
    fn cells(buffer: &Buffer, origin: Pos, size: Size) -> Vec<Option<Cell>> {
        (0..size.height)
            .flat_map(|dy| (0..size.width).map(move |dx| (dx, dy)))
            .map(|(dx, dy)| {
                let at = Pos {
                    x: origin.x + i32::try_from(dx).expect("width fits i32"),
                    y: origin.y + i32::try_from(dy).expect("height fits i32"),
                };
                buffer.cell(at).cloned()
            })
            .collect()
    }

    /// TE-003, scenarios 1 and 2: a diagram holding a box and a line, drawn twice into equal
    /// windows, produces equal buffers.
    #[test]
    fn drawing_the_same_diagram_twice_produces_equal_buffers() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 10,
            height: 5,
        };
        let mut diagram = Diagram::new();
        diagram.add(Shape::Box {
            at: Pos { x: 0, y: 0 },
            size: Size {
                width: 4,
                height: 3,
            },
            stroke: light(),
            fill: None,
        });
        diagram.add(Shape::Line {
            at: Pos { x: 0, y: 4 },
            len: 5,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });

        let mut first = Buffer::new(origin, size);
        diagram.draw(&mut first);
        let mut second = Buffer::new(origin, size);
        diagram.draw(&mut second);

        assert_eq!(cells(&first, origin, size), cells(&second, origin, size));
    }

    /// Scenario 3: an empty diagram leaves its buffer exactly as it was.
    #[test]
    fn an_empty_diagram_leaves_its_buffer_untouched() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 3,
            height: 3,
        };
        let mut buffer = Buffer::new(origin, size);
        Diagram::new().draw(&mut buffer);

        assert_eq!(
            cells(&buffer, origin, size),
            vec![None; (size.width * size.height) as usize]
        );
    }

    /// TE-002, scenario 4: a box partly outside the window draws what falls inside and nothing
    /// else, with no error.
    #[test]
    fn a_box_partly_outside_the_window_draws_only_what_falls_inside() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 3,
            height: 3,
        };
        let mut diagram = Diagram::new();
        diagram.add(Shape::Box {
            at: Pos { x: 1, y: 1 },
            size: Size {
                width: 4,
                height: 4,
            },
            stroke: light(),
            fill: None,
        });

        let mut buffer = Buffer::new(origin, size);
        diagram.draw(&mut buffer);

        assert!(buffer.cell(Pos { x: 1, y: 1 }).is_some());
        assert!(buffer.cell(Pos { x: 4, y: 4 }).is_none());
    }

    /// TE-005, scenario 5: a box drawn through a diagram matches the same `BoxShape` drawn
    /// directly.
    #[test]
    fn a_box_shape_matches_the_core_box_drawn_directly() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 3,
        };
        let mut diagram = Diagram::new();
        diagram.add(Shape::Box {
            at: origin,
            size,
            stroke: light(),
            fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
        });
        let mut actual = Buffer::new(origin, size);
        diagram.draw(&mut actual);

        let mut expected = Buffer::new(origin, size);
        BoxShape {
            at: origin,
            size,
            stroke: light(),
            fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
        }
        .draw(&mut Layer::new(&mut expected, StampMode::Above));

        assert_eq!(
            render(&actual, &GlyphCatalog::light(), origin, size),
            render(&expected, &GlyphCatalog::light(), origin, size)
        );
    }

    /// TE-005: a line drawn through a diagram matches the same `Line` drawn directly.
    #[test]
    fn a_line_shape_matches_the_core_line_drawn_directly() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 5,
            height: 1,
        };
        let mut diagram = Diagram::new();
        diagram.add(Shape::Line {
            at: origin,
            len: 5,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });
        let mut actual = Buffer::new(origin, size);
        diagram.draw(&mut actual);

        let mut expected = Buffer::new(origin, size);
        Line {
            at: origin,
            len: 5,
            orientation: Orientation::Horizontal,
            stroke: light(),
        }
        .draw(&mut Layer::new(&mut expected, StampMode::Above));

        assert_eq!(
            render(&actual, &GlyphCatalog::light(), origin, size),
            render(&expected, &GlyphCatalog::light(), origin, size)
        );
    }

    /// TE-005: a connector drawn through a diagram matches the same `Connector` drawn directly, both
    /// endpoints included.
    #[test]
    fn a_connector_shape_matches_the_core_connector_drawn_directly() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 5,
            height: 4,
        };
        let from = || Endpoint {
            at: Pos { x: 0, y: 0 },
            leaving: Direction::Down,
            terminal: Terminal::Glyph {
                glyph: Glyph::new("▼").expect("one glyph"),
            },
        };
        let to = || Endpoint {
            at: Pos { x: 4, y: 3 },
            leaving: Direction::Left,
            terminal: Terminal::Glyph {
                glyph: Glyph::new("►").expect("one glyph"),
            },
        };

        let mut diagram = Diagram::new();
        diagram.add(Shape::Connector {
            from: from(),
            to: to(),
            stroke: light(),
        });
        let mut actual = Buffer::new(origin, size);
        diagram.draw(&mut actual);

        let mut expected = Buffer::new(origin, size);
        Connector {
            from: from().into(),
            to: to().into(),
            stroke: light(),
        }
        .draw(&mut Layer::new(&mut expected, StampMode::Above));

        assert_eq!(
            render(&actual, &GlyphCatalog::light(), origin, size),
            render(&expected, &GlyphCatalog::light(), origin, size)
        );
    }

    /// TE-001: adding three shapes to one diagram yields three identities that differ from one
    /// another and read as `#1`, `#2`, `#3` in the order added.
    #[test]
    fn adding_three_shapes_yields_three_identities_in_order() {
        let mut diagram = Diagram::new();
        let first = diagram.add(Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });
        let second = diagram.add(Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });
        let third = diagram.add(Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });

        assert_eq!(first.to_string(), "#1");
        assert_eq!(second.to_string(), "#2");
        assert_eq!(third.to_string(), "#3");
        assert_ne!(first, second);
        assert_ne!(second, third);
        assert_ne!(first, third);
    }

    /// Spec.md US1 scenario 3: adding the same shape value twice yields two different identities.
    #[test]
    fn adding_the_same_shape_value_twice_yields_two_different_identities() {
        let shape = || Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        };
        let mut diagram = Diagram::new();
        let first = diagram.add(shape());
        let second = diagram.add(shape());

        assert_ne!(first, second);
    }

    /// Two overlapping boxes, each filled with its own glyph, so which one is front-most decides
    /// the shared cells rather than leaving both interior sides open (as two unfilled boxes with
    /// the same stroke do, order-independently).
    fn overlapping_boxes() -> (Shape, Shape) {
        (
            Shape::Box {
                at: Pos { x: 0, y: 0 },
                size: Size {
                    width: 4,
                    height: 3,
                },
                stroke: light(),
                fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
            },
            Shape::Box {
                at: Pos { x: 2, y: 1 },
                size: Size {
                    width: 4,
                    height: 3,
                },
                stroke: light(),
                fill: Some(Glyph::new("▓").expect("\"▓\" is one glyph")),
            },
        )
    }

    fn overlapping_core_boxes() -> (BoxShape, BoxShape) {
        (
            BoxShape {
                at: Pos { x: 0, y: 0 },
                size: Size {
                    width: 4,
                    height: 3,
                },
                stroke: light(),
                fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
            },
            BoxShape {
                at: Pos { x: 2, y: 1 },
                size: Size {
                    width: 4,
                    height: 3,
                },
                stroke: light(),
                fill: Some(Glyph::new("▓").expect("\"▓\" is one glyph")),
            },
        )
    }

    /// TE-001, scenario 1, SC-005: two overlapping boxes drawn front to back with `Below` produce
    /// the buffer that stamping the same two core shapes back to front with `Above` produces.
    #[test]
    fn front_to_back_with_below_equals_back_to_front_with_above() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        diagram.add(a);
        diagram.add(b);
        let mut actual = Buffer::new(origin, size);
        diagram.draw(&mut actual);

        let (core_a, core_b) = overlapping_core_boxes();
        let mut expected = Buffer::new(origin, size);
        core_a.draw(&mut Layer::new(&mut expected, StampMode::Above));
        core_b.draw(&mut Layer::new(&mut expected, StampMode::Above));

        assert_eq!(cells(&actual, origin, size), cells(&expected, origin, size));
    }

    /// TE-004, scenarios 2 and 5: the same two overlapping boxes in opposite orders produce
    /// different buffers, and in each the front-most shape's stroke decides the shared cells.
    #[test]
    fn opposite_orders_produce_different_buffers() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut a_then_b = Diagram::new();
        a_then_b.add(a);
        a_then_b.add(b);
        let mut a_then_b_buffer = Buffer::new(origin, size);
        a_then_b.draw(&mut a_then_b_buffer);

        let (a, b) = overlapping_boxes();
        let mut b_then_a = Diagram::new();
        b_then_a.add(b);
        b_then_a.add(a);
        let mut b_then_a_buffer = Buffer::new(origin, size);
        b_then_a.draw(&mut b_then_a_buffer);

        assert_ne!(
            cells(&a_then_b_buffer, origin, size),
            cells(&b_then_a_buffer, origin, size)
        );
    }

    /// Scenarios 3 and 4: a crossing is composition, not occlusion — a horizontal and a vertical
    /// line that cross make a junction glyph, and a filled box in front of a line hides it
    /// wherever the box's interior covers it, while the box's border still composes with the
    /// line into a junction where the two meet.
    #[test]
    fn a_crossing_composes_and_a_filled_box_occludes() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 5,
            height: 5,
        };

        let mut crossing = Diagram::new();
        crossing.add(Shape::Line {
            at: Pos { x: 0, y: 2 },
            len: 5,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });
        crossing.add(Shape::Line {
            at: Pos { x: 2, y: 0 },
            len: 5,
            orientation: Orientation::Vertical,
            stroke: light(),
        });
        let mut crossing_buffer = Buffer::new(origin, size);
        crossing.draw(&mut crossing_buffer);
        assert_eq!(
            render(&crossing_buffer, &GlyphCatalog::light(), origin, size),
            "  │  \n  │  \n──┼──\n  │  \n  │  \n"
        );

        let mut occluding = Diagram::new();
        occluding.add(Shape::Line {
            at: Pos { x: 2, y: 0 },
            len: 5,
            orientation: Orientation::Vertical,
            stroke: light(),
        });
        occluding.add(Shape::Box {
            at: Pos { x: 1, y: 1 },
            size: Size {
                width: 3,
                height: 3,
            },
            stroke: light(),
            fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
        });
        let mut occluding_buffer = Buffer::new(origin, size);
        occluding.draw(&mut occluding_buffer);
        assert_eq!(
            render(&occluding_buffer, &GlyphCatalog::light(), origin, size),
            "  │  \n ┌┴┐ \n │░│ \n └┬┘ \n  │  \n"
        );
    }

    /// TE-002: two partially overlapping opaque boxes, drawn before and after the back one moves
    /// forward, produce different buffers, and the second equals what the same two boxes added in
    /// the opposite order produce.
    #[test]
    fn moving_the_back_one_forward_matches_adding_them_in_the_opposite_order() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        let back = diagram.add(a);
        diagram.add(b);
        let mut before = Buffer::new(origin, size);
        diagram.draw(&mut before);

        diagram.forward(&back);
        let mut after = Buffer::new(origin, size);
        diagram.draw(&mut after);

        assert_ne!(cells(&before, origin, size), cells(&after, origin, size));

        let (a, b) = overlapping_boxes();
        let mut opposite = Diagram::new();
        opposite.add(b);
        opposite.add(a);
        let mut opposite_buffer = Buffer::new(origin, size);
        opposite.draw(&mut opposite_buffer);

        assert_eq!(
            cells(&after, origin, size),
            cells(&opposite_buffer, origin, size)
        );
    }

    /// TE-003: the same expected buffer comes from moving the front one backward instead, against
    /// the same two boxes.
    #[test]
    fn moving_the_front_one_backward_matches_moving_the_back_one_forward() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        diagram.add(a);
        let front = diagram.add(b);
        diagram.backward(&front);
        let mut buffer = Buffer::new(origin, size);
        diagram.draw(&mut buffer);

        let (a, b) = overlapping_boxes();
        let mut opposite = Diagram::new();
        opposite.add(b);
        opposite.add(a);
        let mut opposite_buffer = Buffer::new(origin, size);
        opposite.draw(&mut opposite_buffer);

        assert_eq!(
            cells(&buffer, origin, size),
            cells(&opposite_buffer, origin, size)
        );
    }

    /// TE-004: moving the front-most forward, and moving the back-most backward, each leave the
    /// drawn buffer unchanged.
    #[test]
    fn moving_the_front_most_forward_or_the_back_most_backward_changes_nothing() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        let back = diagram.add(a);
        let front = diagram.add(b);
        let mut before = Buffer::new(origin, size);
        diagram.draw(&mut before);

        diagram.forward(&front);
        let mut after_forward = Buffer::new(origin, size);
        diagram.draw(&mut after_forward);
        assert_eq!(
            cells(&before, origin, size),
            cells(&after_forward, origin, size)
        );

        diagram.backward(&back);
        let mut after_backward = Buffer::new(origin, size);
        diagram.draw(&mut after_backward);
        assert_eq!(
            cells(&before, origin, size),
            cells(&after_backward, origin, size)
        );
    }

    /// TE-004, edge case: a diagram holding one shape is unchanged by either move, since that
    /// shape is both front-most and back-most.
    #[test]
    fn a_diagram_holding_one_shape_is_unchanged_by_either_move() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 4,
            height: 3,
        };
        let mut diagram = Diagram::new();
        let only = diagram.add(Shape::Box {
            at: Pos { x: 0, y: 0 },
            size: Size {
                width: 4,
                height: 3,
            },
            stroke: light(),
            fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
        });
        let mut before = Buffer::new(origin, size);
        diagram.draw(&mut before);

        diagram.forward(&only);
        diagram.backward(&only);
        let mut after = Buffer::new(origin, size);
        diagram.draw(&mut after);

        assert_eq!(cells(&before, origin, size), cells(&after, origin, size));
    }

    /// TE-005, edge case: an identity kept from another diagram changes nothing through either
    /// method, with no panic.
    #[test]
    fn an_identity_from_another_diagram_changes_nothing_and_does_not_panic() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        diagram.add(a);
        diagram.add(b);
        let mut before = Buffer::new(origin, size);
        diagram.draw(&mut before);

        let mut other = Diagram::new();
        let foreign = other.add(Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });

        diagram.forward(&foreign);
        diagram.backward(&foreign);
        let mut after = Buffer::new(origin, size);
        diagram.draw(&mut after);

        assert_eq!(cells(&before, origin, size), cells(&after, origin, size));
    }

    /// TE-005, edge case: an empty diagram is unchanged by either method, with no panic.
    #[test]
    fn an_empty_diagram_is_unchanged_by_either_move() {
        let mut other = Diagram::new();
        let foreign = other.add(Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });

        let mut diagram = Diagram::new();
        diagram.forward(&foreign);
        diagram.backward(&foreign);

        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 3,
            height: 3,
        };
        let mut buffer = Buffer::new(origin, size);
        diagram.draw(&mut buffer);

        assert_eq!(
            cells(&buffer, origin, size),
            vec![None; (size.width * size.height) as usize]
        );
    }

    /// TE-006: a shape moved forward and then backward by the same identity draws exactly what it
    /// drew at the start.
    #[test]
    fn moving_a_shape_forward_then_backward_restores_the_original_drawing() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        let back = diagram.add(a);
        diagram.add(b);
        let mut before = Buffer::new(origin, size);
        diagram.draw(&mut before);

        diagram.forward(&back);
        diagram.backward(&back);
        let mut after = Buffer::new(origin, size);
        diagram.draw(&mut after);

        assert_eq!(cells(&before, origin, size), cells(&after, origin, size));
    }

    /// Edge case: two unfilled boxes with the same stroke whose shared cells every side leaves
    /// `Unset` — an inner box entirely inside an outer box's interior, so their border cells never
    /// coincide — draw identically before and after a reorder.
    #[test]
    fn two_unfilled_boxes_with_no_shared_cell_draw_identically_regardless_of_order() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 5,
        };
        let outer = || Shape::Box {
            at: Pos { x: 0, y: 0 },
            size: Size {
                width: 6,
                height: 5,
            },
            stroke: light(),
            fill: None,
        };
        let inner = || Shape::Box {
            at: Pos { x: 2, y: 2 },
            size: Size {
                width: 2,
                height: 2,
            },
            stroke: light(),
            fill: None,
        };

        let mut outer_then_inner = Diagram::new();
        outer_then_inner.add(outer());
        outer_then_inner.add(inner());
        let mut a = Buffer::new(origin, size);
        outer_then_inner.draw(&mut a);

        let mut inner_then_outer = Diagram::new();
        inner_then_outer.add(inner());
        inner_then_outer.add(outer());
        let mut b = Buffer::new(origin, size);
        inner_then_outer.draw(&mut b);

        assert_eq!(cells(&a, origin, size), cells(&b, origin, size));
    }

    // ------------------------------------------------------ a figure displaced by a delta

    /// Draws `shapes` into a fresh window, in the order given, so that a figure is observed the
    /// only way this crate lets it be observed. Both sides of every comparison below arrive
    /// through here: the figure displaced, and the same figure added where it landed.
    fn drawn(shapes: Vec<Shape>, origin: Pos, size: Size) -> Buffer {
        let mut diagram = Diagram::new();
        for shape in shapes {
            diagram.add(shape);
        }
        draw_of(&diagram, origin, size)
    }

    /// Draws a diagram the caller already holds, for a claim about what a change to it did.
    fn draw_of(diagram: &Diagram, origin: Pos, size: Size) -> Buffer {
        let mut buffer = Buffer::new(origin, size);
        diagram.draw(&mut buffer);
        buffer
    }

    /// The positions where two buffers of one window differ, so that a claim about which cells a
    /// change reached can be made by coordinates rather than by reading two pictures side by side.
    fn differing(before: &Buffer, after: &Buffer, origin: Pos, size: Size) -> Vec<Pos> {
        (0..size.height)
            .flat_map(|dy| (0..size.width).map(move |dx| (dx, dy)))
            .map(|(dx, dy)| Pos {
                x: origin.x + i32::try_from(dx).expect("width fits i32"),
                y: origin.y + i32::try_from(dy).expect("height fits i32"),
            })
            .filter(|at| before.cell(*at) != after.cell(*at))
            .collect()
    }

    /// Three filled boxes that all overlap one another, so which of them is front-most decides the
    /// cells they share and a change of order changes the picture. The first is the back-most and
    /// the last the front-most, and the second overlaps both.
    fn three_overlapping_boxes() -> (Shape, Shape, Shape) {
        let filled_box = |at: Pos, fill: &str| Shape::Box {
            at,
            size: Size {
                width: 4,
                height: 3,
            },
            stroke: light(),
            fill: Some(Glyph::new(fill).expect("one glyph")),
        };
        (
            filled_box(Pos { x: 0, y: 0 }, "░"),
            filled_box(Pos { x: 2, y: 1 }, "▓"),
            filled_box(Pos { x: 0, y: 1 }, "▒"),
        )
    }

    /// An identity no diagram in these tests holds, and the one the specification's cases mean by
    /// an identity from another diagram.
    ///
    /// It is the **third** identity another diagram issued rather than its first, because
    /// `ShapeId` is a string: an identity from elsewhere matches nothing here only because its
    /// number differs, and a diagram that issued one shape issues `#1`, which is exactly the
    /// identity a diagram holding two shapes has already used.
    fn a_foreign_identity() -> ShapeId {
        let a_line = || Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        };
        let mut other = Diagram::new();
        other.add(a_line());
        other.add(a_line());
        other.add(a_line())
    }

    /// User Story 1, spec's B3.1 scenario, SC-004: a box displaced two cells right draws exactly
    /// what the same box added at the displaced position draws.
    ///
    /// The expected picture is built by adding the box where it landed rather than pinned as text,
    /// so what is asserted is where a displacement puts a figure and not how a box draws. A
    /// displacement that quietly did nothing would draw the box where it already stood, and the two
    /// pictures would differ.
    #[test]
    fn a_displaced_box_draws_where_the_same_box_at_that_position_would_draw() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 9,
            height: 3,
        };
        let box_at = |x: i32| Shape::Box {
            at: Pos { x, y: 0 },
            size: Size {
                width: 4,
                height: 3,
            },
            stroke: light(),
            fill: None,
        };

        let moved = box_at(1).displaced_by(Delta { dx: 2, dy: 0 });

        assert_eq!(
            cells(&drawn(vec![moved], origin, size), origin, size),
            cells(&drawn(vec![box_at(3)], origin, size), origin, size)
        );
    }

    /// User Story 1, spec's B3.2 scenario, SC-004: a connector displaced two cells down draws
    /// exactly what the same connector added with **both** endpoints at `y + 2` draws.
    ///
    /// Both endpoints is the whole claim, and it is why the expected picture is built from the two
    /// positions rather than pinned as text. A displacement that moved one endpoint draws a
    /// connector between two rows, and one that moved neither is the silent no-op the previous
    /// system shipped along with a `// TODO: implement it`. Either passes a comparison against a
    /// picture of a connector that never moved, so this is the one neither passes.
    #[test]
    fn a_displaced_connector_draws_with_both_endpoints_moved() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 7,
            height: 5,
        };
        let connector = |from: Pos, to: Pos| Shape::Connector {
            from: Endpoint {
                at: from,
                leaving: Direction::Right,
                terminal: Terminal::Glyph {
                    glyph: Glyph::new("◄").expect("one glyph"),
                },
            },
            to: Endpoint {
                at: to,
                leaving: Direction::Left,
                terminal: Terminal::Glyph {
                    glyph: Glyph::new("►").expect("one glyph"),
                },
            },
            stroke: light(),
        };

        let moved =
            connector(Pos { x: 1, y: 1 }, Pos { x: 5, y: 1 }).displaced_by(Delta { dx: 0, dy: 2 });

        assert_eq!(
            cells(&drawn(vec![moved], origin, size), origin, size),
            cells(
                &drawn(
                    vec![connector(Pos { x: 1, y: 3 }, Pos { x: 5, y: 3 })],
                    origin,
                    size
                ),
                origin,
                size
            )
        );
    }

    /// User Story 1, spec's B3.3 scenario: displacing a figure a diagram holds changes no cell of
    /// it. A displacement builds a value; putting that value back under an identity is what changes
    /// anything. The second half of the rule is T026, which needs `replace` to exist.
    ///
    /// The `assert_ne!` is what keeps the test honest: without it a `displaced_by` that moved
    /// nothing would satisfy "changed no cell" by doing exactly that, and the rule would go
    /// unchecked.
    #[test]
    fn displacing_a_figure_the_diagram_holds_changes_no_cell_of_it() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        diagram.add(a.clone());
        diagram.add(b);
        let mut before = Buffer::new(origin, size);
        diagram.draw(&mut before);

        let displaced = a.displaced_by(Delta { dx: 1, dy: 2 });
        let mut after = Buffer::new(origin, size);
        diagram.draw(&mut after);

        assert_eq!(cells(&before, origin, size), cells(&after, origin, size));
        assert_ne!(displaced, a);
    }

    // ------------------------------------------- reading a figure back, and the two changes

    /// User Story 2, spec's B4.1 scenario: `get` on the identity `add` handed back returns a figure
    /// equal by value to the one added.
    ///
    /// Compared by value rather than by picture, because this is the only rule in the slice no
    /// picture can show. The widened derives are what make it sayable at all, and what comes back
    /// is the bare figure: the identity and the place in the order are the diagram's, held beside
    /// the figure rather than inside it.
    #[test]
    fn get_returns_the_figure_the_addition_named() {
        let (a, _b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        let id = diagram.add(a.clone());

        assert_eq!(diagram.get(&id), Some(&a));
    }

    /// User Story 2, spec's B4.2 scenario, SC-003: `get` on an identity this diagram does not hold
    /// gives nothing, and the picture it draws is the one it drew before.
    ///
    /// The identity is one another diagram issued, which is the case the specification means.
    #[test]
    fn get_on_an_identity_from_another_diagram_gives_nothing_and_changes_nothing() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        diagram.add(a);
        diagram.add(b);
        let before = draw_of(&diagram, origin, size);

        assert_eq!(diagram.get(&a_foreign_identity()), None);
        assert_eq!(
            cells(&before, origin, size),
            cells(&draw_of(&diagram, origin, size), origin, size)
        );
    }

    /// User Story 3, spec's B1.1 scenario, SC-001: a diagram of several figures, drawn before and
    /// after one is taken out, produces different buffers, and the figures that stayed draw exactly
    /// what they drew on their own.
    ///
    /// Three overlapping boxes rather than a row, and the one taken out is the first of the three
    /// rather than a figure in the middle. That is what makes the test say something a swap with
    /// the last entry could not pass: closing the gap leaves the survivors in the order they were,
    /// so the one that was in front is still in front, and swapping the removed entry with the
    /// back-most would hand the diagram the other two pictures instead.
    #[test]
    fn taking_a_shape_out_changes_the_picture_and_leaves_the_rest_drawing_what_they_drew() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (first, second, third) = three_overlapping_boxes();

        let mut diagram = Diagram::new();
        let taken_out = diagram.add(first);
        diagram.add(second.clone());
        diagram.add(third.clone());
        let before = draw_of(&diagram, origin, size);

        diagram.remove(&taken_out);
        let after = draw_of(&diagram, origin, size);

        assert_ne!(cells(&before, origin, size), cells(&after, origin, size));
        assert_eq!(
            cells(&after, origin, size),
            cells(&drawn(vec![second, third], origin, size), origin, size)
        );
    }

    /// User Story 3, spec's B1.2 scenario, SC-003: taking out an identity this diagram does not
    /// hold leaves the buffer exactly as it was, with no error, no report and no panic. The
    /// identity is one another diagram issued, which is the case worth running: a well-formed
    /// value that matches nothing here.
    #[test]
    fn taking_out_an_identity_from_another_diagram_changes_nothing_and_does_not_panic() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        diagram.add(a);
        diagram.add(b);
        let before = draw_of(&diagram, origin, size);

        diagram.remove(&a_foreign_identity());

        assert_eq!(
            cells(&before, origin, size),
            cells(&draw_of(&diagram, origin, size), origin, size)
        );
    }

    /// User Story 3, spec's B1.3 scenario, SC-005: take `#1` out, add a figure, and the identity
    /// handed back is `#3` rather than `#1`.
    ///
    /// Asserted by the identity's own text rather than by a picture, and it needs no code beyond
    /// the absence of a decrement, because `add` already increments before use.
    #[test]
    fn an_identity_is_never_handed_out_again_after_a_removal() {
        let a_line = || Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        };

        let mut diagram = Diagram::new();
        let first = diagram.add(a_line());
        diagram.add(a_line());
        assert_eq!(first.to_string(), "#1");

        diagram.remove(&first);
        let after_the_removal = diagram.add(a_line());

        assert_eq!(after_the_removal.to_string(), "#3");
    }

    /// Edge case: the last shape taken out leaves an empty diagram, and drawing an empty diagram
    /// leaves the buffer as it was. The rule `an_empty_diagram_leaves_its_buffer_untouched` already
    /// pins, reached here through a removal rather than through a diagram never given anything.
    #[test]
    fn taking_out_the_last_shape_leaves_an_empty_diagram() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, _b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        let only = diagram.add(a);

        diagram.remove(&only);

        assert_eq!(
            cells(&draw_of(&diagram, origin, size), origin, size),
            vec![None; (size.width * size.height) as usize]
        );
    }

    /// User Story 4, spec's B2.1 scenario, SC-002: a box put back as a wider box draws exactly what
    /// that wider box added on its own produces.
    ///
    /// Pinned against the wider box's own picture rather than against the box it replaced, which is
    /// what makes the claim about the figure handed in and not about a difference between two.
    #[test]
    fn a_box_put_back_as_a_wider_box_draws_that_wider_box() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 9,
            height: 3,
        };
        let box_of = |width: u32| Shape::Box {
            at: Pos { x: 1, y: 0 },
            size: Size { width, height: 3 },
            stroke: light(),
            fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
        };

        let mut diagram = Diagram::new();
        let id = diagram.add(box_of(4));
        diagram.replace(&id, box_of(7));

        assert_eq!(
            cells(&draw_of(&diagram, origin, size), origin, size),
            cells(&drawn(vec![box_of(7)], origin, size), origin, size)
        );
    }

    /// User Story 4, spec's B2.2 scenario, SC-002: a box put back as a line draws the line, kind
    /// included, and nothing of the previous figure survives.
    ///
    /// The pair the specification draws by hand and calls hypothetical, each side pinned against
    /// the figure handed in rather than against the other, which is what turns "nothing of the
    /// previous figure survives" into a checked claim rather than a comparison of two pictures.
    #[test]
    fn a_box_put_back_as_a_line_draws_the_line() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 4,
            height: 3,
        };
        let the_box = || Shape::Box {
            at: Pos { x: 0, y: 0 },
            size: Size {
                width: 4,
                height: 3,
            },
            stroke: light(),
            fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
        };
        let the_line = || Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 4,
            orientation: Orientation::Horizontal,
            stroke: light(),
        };

        let mut diagram = Diagram::new();
        let id = diagram.add(the_box());
        diagram.replace(&id, the_line());

        assert_eq!(
            cells(&draw_of(&diagram, origin, size), origin, size),
            cells(&drawn(vec![the_line()], origin, size), origin, size)
        );
    }

    /// User Story 4, spec's B2.3 scenario: a figure overlapping another, put back under its own
    /// identity unchanged, resolves the overlap as it did.
    ///
    /// This is what shows a replacement is not a reorder, and the second assertion says so
    /// directly: it holds up the order a remove-and-add would have produced as the picture that
    /// replacement must **not** draw. Two figures would not have been enough, since removing the
    /// front-most of two and adding it back leaves the order it was.
    #[test]
    fn a_figure_put_back_unchanged_resolves_its_overlap_as_it_did() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b, c) = three_overlapping_boxes();
        let mut diagram = Diagram::new();
        diagram.add(a.clone());
        let middle = diagram.add(b.clone());
        diagram.add(c.clone());
        let before = draw_of(&diagram, origin, size);

        diagram.replace(&middle, b.clone());
        let after = draw_of(&diagram, origin, size);

        assert_eq!(cells(&before, origin, size), cells(&after, origin, size));
        assert_ne!(
            cells(&after, origin, size),
            cells(&drawn(vec![a, c, b], origin, size), origin, size)
        );
    }

    /// User Story 4, spec's B2.4 scenario, SC-003: a shape put under an identity this diagram does
    /// not hold leaves the picture alone **and adds nothing**.
    ///
    /// The figure handed in is placed where it would be plainly visible, so a `replace` that fell
    /// back to removing the old entry and adding the new one would fail on the picture rather than
    /// on a count. The identity assertion is the other half: `#1` still names the figure it always
    /// named, so there is no way to name a shape into existence.
    #[test]
    fn a_shape_put_under_a_foreign_identity_is_neither_drawn_nor_added() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        diagram.add(a.clone());
        diagram.add(b);
        let before = draw_of(&diagram, origin, size);

        diagram.replace(
            &a_foreign_identity(),
            Shape::Box {
                at: Pos { x: 1, y: 1 },
                size: Size {
                    width: 3,
                    height: 3,
                },
                stroke: light(),
                fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
            },
        );
        let after = draw_of(&diagram, origin, size);

        assert_eq!(cells(&before, origin, size), cells(&after, origin, size));
        assert_eq!(diagram.get(&ShapeId::new("#1")), Some(&a));
    }

    /// User Story 1, spec's B3.3 scenario, second half: draw, displace, `replace`, and the picture
    /// is the one the same three figures draw with the middle one standing where the displacement
    /// put it.
    ///
    /// It lands beside the replacement rather than beside the displacement because it is the half
    /// that needs `replace` to exist. The reach is then pinned by coordinates: the cells the
    /// figure held before and the cells it holds now, and not one more. A change reaching a cell
    /// of either box, which is what a move implemented as a removal and an addition would do, is
    /// outside that set.
    #[test]
    fn putting_a_displaced_figure_back_reaches_only_the_cells_that_figure_holds() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 11,
            height: 3,
        };
        let filled_box = |x: i32, fill: &str| Shape::Box {
            at: Pos { x, y: 0 },
            size: Size {
                width: 3,
                height: 3,
            },
            stroke: light(),
            fill: Some(Glyph::new(fill).expect("one glyph")),
        };
        let the_line = |x: i32| Shape::Line {
            at: Pos { x, y: 1 },
            len: 5,
            orientation: Orientation::Horizontal,
            stroke: light(),
        };

        let mut diagram = Diagram::new();
        diagram.add(filled_box(0, "░"));
        let middle = diagram.add(the_line(3));
        diagram.add(filled_box(8, "▓"));
        let before = draw_of(&diagram, origin, size);

        let moved = the_line(3).displaced_by(Delta { dx: 2, dy: 0 });
        diagram.replace(&middle, moved.clone());
        let after = draw_of(&diagram, origin, size);

        assert_eq!(
            cells(&after, origin, size),
            cells(
                &drawn(
                    vec![filled_box(0, "░"), moved, filled_box(8, "▓")],
                    origin,
                    size
                ),
                origin,
                size
            )
        );

        let held_by_the_line = |at: Pos| at.y == 1 && (3..=9).contains(&at.x);
        let reached = differing(&before, &after, origin, size);
        assert!(
            !reached.is_empty(),
            "the displacement reached nothing at all"
        );
        assert!(
            reached.iter().all(|at| held_by_the_line(*at)),
            "the change reached outside the displaced figure: {reached:?}"
        );
    }
}
