//! The diagram: an ordered set of shapes, drawable into a buffer the caller gives it. See
//! [`docs/diagram-model.md`](../../../docs/diagram-model.md) and
//! [ADR-0042](../../../docs/decisions/0042-draw-a-diagram-front-to-back-into-a-given-window.md).

use std::fmt;

use monospace_core::{Buffer, Layer, StampMode};

use crate::Shape;

/// A shape's identity: normally generated by the diagram that placed it and unique within it
/// (FR-001, FR-002), though [`ShapeId::new`] can also build one directly from its text.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ShapeId(String);

impl ShapeId {
    /// Builds an identity directly from its text — `"#1"`, `"#2"`, and so on.
    pub fn new(text: impl Into<String>) -> Self {
        Self(text.into())
    }
}

impl fmt::Display for ShapeId {
    /// Writes the identity as `#1`, `#2`, and so on.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

/// One entry of a diagram's order: a shape and the identity the diagram gave it.
struct Placed {
    id: ShapeId,
    shape: Shape,
}

/// A diagram: an ordered set of shapes, and nothing else — no buffer, no glyph catalog, no
/// rendered picture (FR-005).
#[derive(Default)]
pub struct Diagram {
    /// The order the shapes draw in. The **last** element is the front of the order (research.md
    /// Q2): it is drawn first and decides a shared cell before anything behind it.
    shapes: Vec<Placed>,
    /// The ordinal the next `add` numbers its identity with.
    next: u32,
}

impl Diagram {
    /// An empty diagram, holding no shapes.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Puts `shape` at the front of the order, in front of everything already there, and returns
    /// the identity the diagram gave it (FR-002, FR-006).
    pub fn add(&mut self, shape: Shape) -> ShapeId {
        self.next += 1;
        let id = ShapeId(format!("#{}", self.next));
        self.shapes.push(Placed {
            id: id.clone(),
            shape,
        });
        id
    }

    /// The place in the order the shape named by `id` stands, or `None` when this diagram holds
    /// no such shape.
    ///
    /// The one search every method naming a shape by its identity goes through. `ShapeId`s are
    /// compared by value, so an identity issued by another diagram is a well-formed value that
    /// matches nothing here — the same answer the model's _Positions_ gives a reference to a shape
    /// that is not there.
    fn find(&self, id: &ShapeId) -> Option<usize> {
        self.shapes.iter().position(|placed| &placed.id == id)
    }

    /// Moves the shape named by `id` one place toward the front of the order. Does nothing when
    /// `id` names no shape here, or when it is already the front-most (FR-007, FR-009, FR-010,
    /// FR-011).
    pub fn forward(&mut self, id: &ShapeId) {
        if let Some(index) = self.find(id)
            && index + 1 < self.shapes.len()
        {
            self.shapes.swap(index, index + 1);
        }
    }

    /// Moves the shape named by `id` one place toward the back of the order. Does nothing when
    /// `id` names no shape here, or when it is already the back-most (FR-008, FR-009, FR-010,
    /// FR-011).
    pub fn backward(&mut self, id: &ShapeId) {
        if let Some(index) = self.find(id)
            && index > 0
        {
            self.shapes.swap(index, index - 1);
        }
    }

    /// The figure named by `id`, or `None` when this diagram holds no such shape.
    ///
    /// The crate's first reader, and the only one: one query by an identity the caller already
    /// holds, and nothing coming back the other way. There is no listing of a diagram's
    /// identities, no count, no order, and no way to ask which shape decided a position.
    ///
    /// It borrows, and there is no `cloned()` beside it. What comes back is the bare figure the
    /// caller added, with the identity and the place in the order held here in the diagram rather
    /// than inside the figure, so nothing about what is returned says where it sits.
    #[must_use]
    pub fn get(&self, id: &ShapeId) -> Option<&Shape> {
        self.find(id).map(|index| &self.shapes[index].shape)
    }

    /// Takes the shape named by `id` out of the diagram, changing nothing else.
    ///
    /// An identity this diagram does not hold changes nothing, with no error, no report and no
    /// panic, which is the same answer the model's _Positions_ gives a reference to a shape that
    /// is not there. The gap is closed, so what remains of the order keeps the order it had: a
    /// removal changes the holding and nothing else.
    ///
    /// It hands back nothing. There is no history and nothing to undo, so putting a figure back
    /// means building it again. The counter is not touched either, so an identity is never handed
    /// out a second time.
    pub fn remove(&mut self, id: &ShapeId) {
        if let Some(index) = self.find(id) {
            self.shapes.remove(index);
        }
    }

    /// Puts `shape` where the shape named by `id` stands, in the same place in the order.
    ///
    /// The identity and the place in the order survive, and everything the previous figure owned
    /// is the new figure's: its kind, its parameters and its position. The diagram never reaches
    /// into a box and widens it, and a replacement may change the kind outright, a box becoming a
    /// line, with nothing of the previous figure surviving it.
    ///
    /// An identity this diagram does not hold changes nothing, and the shape handed in is not
    /// added either, so there is no way to name a shape into existence. It takes the shape by
    /// value and hands back nothing, for the reason [`Diagram::remove`] does.
    pub fn replace(&mut self, id: &ShapeId, shape: Shape) {
        if let Some(index) = self.find(id) {
            self.shapes[index].shape = shape;
        }
    }

    /// Draws every shape into `buffer`, front to back, stamping every cell with
    /// [`StampMode::Below`] (FR-010 to FR-012). Drawing changes nothing about this diagram
    /// (FR-015), so two drawings into equal windows produce equal buffers.
    ///
    /// The diagram is what a connector's endpoints resolve through, which is why it is the one that
    /// hands itself to each figure. A connector with an endpoint that does not resolve — an identity
    /// this diagram does not hold, or a kind that answers no such anchor — is **not drawn at all**,
    /// and every other shape draws exactly what it drew. There is no error, no report and no way
    /// to ask which figures were dropped; see
    /// [#88](https://github.com/andresmoschini/monospace/issues/88).
    pub fn draw(&self, buffer: &mut Buffer) {
        let mut layer = Layer::new(buffer, StampMode::Below);
        for placed in self.shapes.iter().rev() {
            placed.shape.draw(&mut layer, self);
        }
    }
}

#[cfg(test)]
mod tests {
    use monospace_core::{
        BoxShape, Buffer, Cell, Connector, Direction, Glyph, GlyphCatalog, Layer, Line,
        Orientation, Pos, Shape as CoreShape, Size, StampMode, Stroke, Terminal, render,
    };

    use super::{Diagram, ShapeId};
    use crate::{Anchor, Delta, Endpoint, Position, Reference, Shape};

    fn light() -> Stroke {
        Stroke::from("light")
    }

    /// Collects every cell of `buffer` over the window `origin`/`size`, so two buffers can be
    /// compared by value even though `Buffer` derives no `PartialEq` (research.md Q7).
    fn cells(buffer: &Buffer, origin: Pos, size: Size) -> Vec<Option<Cell>> {
        (0..size.height)
            .flat_map(|dy| (0..size.width).map(move |dx| (dx, dy)))
            .map(|(dx, dy)| {
                let at = Pos {
                    x: origin.x + i32::try_from(dx).expect("width fits i32"),
                    y: origin.y + i32::try_from(dy).expect("height fits i32"),
                };
                buffer.cell(at).cloned()
            })
            .collect()
    }

    /// TE-003, scenarios 1 and 2: a diagram holding a box and a line, drawn twice into equal
    /// windows, produces equal buffers.
    #[test]
    fn drawing_the_same_diagram_twice_produces_equal_buffers() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 10,
            height: 5,
        };
        let mut diagram = Diagram::new();
        diagram.add(Shape::Box {
            at: Pos { x: 0, y: 0 },
            size: Size {
                width: 4,
                height: 3,
            },
            stroke: light(),
            fill: None,
        });
        diagram.add(Shape::Line {
            at: Pos { x: 0, y: 4 },
            len: 5,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });

        let mut first = Buffer::new(origin, size);
        diagram.draw(&mut first);
        let mut second = Buffer::new(origin, size);
        diagram.draw(&mut second);

        assert_eq!(cells(&first, origin, size), cells(&second, origin, size));
    }

    /// Scenario 3: an empty diagram leaves its buffer exactly as it was.
    #[test]
    fn an_empty_diagram_leaves_its_buffer_untouched() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 3,
            height: 3,
        };
        let mut buffer = Buffer::new(origin, size);
        Diagram::new().draw(&mut buffer);

        assert_eq!(
            cells(&buffer, origin, size),
            vec![None; (size.width * size.height) as usize]
        );
    }

    /// TE-002, scenario 4: a box partly outside the window draws what falls inside and nothing
    /// else, with no error.
    #[test]
    fn a_box_partly_outside_the_window_draws_only_what_falls_inside() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 3,
            height: 3,
        };
        let mut diagram = Diagram::new();
        diagram.add(Shape::Box {
            at: Pos { x: 1, y: 1 },
            size: Size {
                width: 4,
                height: 4,
            },
            stroke: light(),
            fill: None,
        });

        let mut buffer = Buffer::new(origin, size);
        diagram.draw(&mut buffer);

        assert!(buffer.cell(Pos { x: 1, y: 1 }).is_some());
        assert!(buffer.cell(Pos { x: 4, y: 4 }).is_none());
    }

    /// TE-005, scenario 5: a box drawn through a diagram matches the same `BoxShape` drawn
    /// directly.
    #[test]
    fn a_box_shape_matches_the_core_box_drawn_directly() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 3,
        };
        let mut diagram = Diagram::new();
        diagram.add(Shape::Box {
            at: origin,
            size,
            stroke: light(),
            fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
        });
        let mut actual = Buffer::new(origin, size);
        diagram.draw(&mut actual);

        let mut expected = Buffer::new(origin, size);
        BoxShape {
            at: origin,
            size,
            stroke: light(),
            fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
        }
        .draw(&mut Layer::new(&mut expected, StampMode::Above));

        assert_eq!(
            render(&actual, &GlyphCatalog::light(), origin, size),
            render(&expected, &GlyphCatalog::light(), origin, size)
        );
    }

    /// TE-005: a line drawn through a diagram matches the same `Line` drawn directly.
    #[test]
    fn a_line_shape_matches_the_core_line_drawn_directly() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 5,
            height: 1,
        };
        let mut diagram = Diagram::new();
        diagram.add(Shape::Line {
            at: origin,
            len: 5,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });
        let mut actual = Buffer::new(origin, size);
        diagram.draw(&mut actual);

        let mut expected = Buffer::new(origin, size);
        Line {
            at: origin,
            len: 5,
            orientation: Orientation::Horizontal,
            stroke: light(),
        }
        .draw(&mut Layer::new(&mut expected, StampMode::Above));

        assert_eq!(
            render(&actual, &GlyphCatalog::light(), origin, size),
            render(&expected, &GlyphCatalog::light(), origin, size)
        );
    }

    /// TE-005: a connector drawn through a diagram matches the same `Connector` drawn directly, both
    /// endpoints included.
    #[test]
    fn a_connector_shape_matches_the_core_connector_drawn_directly() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 5,
            height: 4,
        };
        let from = || Endpoint {
            at: Pos { x: 0, y: 0 }.into(),
            leaving: Direction::Down,
            terminal: Terminal::Glyph {
                glyph: Glyph::new("▼").expect("one glyph"),
            },
        };
        let to = || Endpoint {
            at: Pos { x: 4, y: 3 }.into(),
            leaving: Direction::Left,
            terminal: Terminal::Glyph {
                glyph: Glyph::new("►").expect("one glyph"),
            },
        };

        let mut diagram = Diagram::new();
        diagram.add(Shape::Connector {
            from: from(),
            to: to(),
            stroke: light(),
        });
        let mut actual = Buffer::new(origin, size);
        diagram.draw(&mut actual);

        let mut expected = Buffer::new(origin, size);
        Connector {
            from: monospace_core::Endpoint {
                at: Pos { x: 0, y: 0 },
                leaving: Direction::Down,
                terminal: Terminal::Glyph {
                    glyph: Glyph::new("▼").expect("one glyph"),
                },
            },
            to: monospace_core::Endpoint {
                at: Pos { x: 4, y: 3 },
                leaving: Direction::Left,
                terminal: Terminal::Glyph {
                    glyph: Glyph::new("►").expect("one glyph"),
                },
            },
            stroke: light(),
        }
        .draw(&mut Layer::new(&mut expected, StampMode::Above));

        assert_eq!(
            render(&actual, &GlyphCatalog::light(), origin, size),
            render(&expected, &GlyphCatalog::light(), origin, size)
        );
    }

    /// TE-001: adding three shapes to one diagram yields three identities that differ from one
    /// another and read as `#1`, `#2`, `#3` in the order added.
    #[test]
    fn adding_three_shapes_yields_three_identities_in_order() {
        let mut diagram = Diagram::new();
        let first = diagram.add(Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });
        let second = diagram.add(Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });
        let third = diagram.add(Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });

        assert_eq!(first.to_string(), "#1");
        assert_eq!(second.to_string(), "#2");
        assert_eq!(third.to_string(), "#3");
        assert_ne!(first, second);
        assert_ne!(second, third);
        assert_ne!(first, third);
    }

    /// Spec.md US1 scenario 3: adding the same shape value twice yields two different identities.
    #[test]
    fn adding_the_same_shape_value_twice_yields_two_different_identities() {
        let shape = || Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        };
        let mut diagram = Diagram::new();
        let first = diagram.add(shape());
        let second = diagram.add(shape());

        assert_ne!(first, second);
    }

    /// Two overlapping boxes, each filled with its own glyph, so which one is front-most decides
    /// the shared cells rather than leaving both interior sides open (as two unfilled boxes with
    /// the same stroke do, order-independently).
    fn overlapping_boxes() -> (Shape, Shape) {
        (
            Shape::Box {
                at: Pos { x: 0, y: 0 },
                size: Size {
                    width: 4,
                    height: 3,
                },
                stroke: light(),
                fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
            },
            Shape::Box {
                at: Pos { x: 2, y: 1 },
                size: Size {
                    width: 4,
                    height: 3,
                },
                stroke: light(),
                fill: Some(Glyph::new("▓").expect("\"▓\" is one glyph")),
            },
        )
    }

    fn overlapping_core_boxes() -> (BoxShape, BoxShape) {
        (
            BoxShape {
                at: Pos { x: 0, y: 0 },
                size: Size {
                    width: 4,
                    height: 3,
                },
                stroke: light(),
                fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
            },
            BoxShape {
                at: Pos { x: 2, y: 1 },
                size: Size {
                    width: 4,
                    height: 3,
                },
                stroke: light(),
                fill: Some(Glyph::new("▓").expect("\"▓\" is one glyph")),
            },
        )
    }

    /// TE-001, scenario 1, SC-005: two overlapping boxes drawn front to back with `Below` produce
    /// the buffer that stamping the same two core shapes back to front with `Above` produces.
    #[test]
    fn front_to_back_with_below_equals_back_to_front_with_above() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        diagram.add(a);
        diagram.add(b);
        let mut actual = Buffer::new(origin, size);
        diagram.draw(&mut actual);

        let (core_a, core_b) = overlapping_core_boxes();
        let mut expected = Buffer::new(origin, size);
        core_a.draw(&mut Layer::new(&mut expected, StampMode::Above));
        core_b.draw(&mut Layer::new(&mut expected, StampMode::Above));

        assert_eq!(cells(&actual, origin, size), cells(&expected, origin, size));
    }

    /// TE-004, scenarios 2 and 5: the same two overlapping boxes in opposite orders produce
    /// different buffers, and in each the front-most shape's stroke decides the shared cells.
    #[test]
    fn opposite_orders_produce_different_buffers() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut a_then_b = Diagram::new();
        a_then_b.add(a);
        a_then_b.add(b);
        let mut a_then_b_buffer = Buffer::new(origin, size);
        a_then_b.draw(&mut a_then_b_buffer);

        let (a, b) = overlapping_boxes();
        let mut b_then_a = Diagram::new();
        b_then_a.add(b);
        b_then_a.add(a);
        let mut b_then_a_buffer = Buffer::new(origin, size);
        b_then_a.draw(&mut b_then_a_buffer);

        assert_ne!(
            cells(&a_then_b_buffer, origin, size),
            cells(&b_then_a_buffer, origin, size)
        );
    }

    /// Scenarios 3 and 4: a crossing is composition, not occlusion — a horizontal and a vertical
    /// line that cross make a junction glyph, and a filled box in front of a line hides it
    /// wherever the box's interior covers it, while the box's border still composes with the
    /// line into a junction where the two meet.
    #[test]
    fn a_crossing_composes_and_a_filled_box_occludes() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 5,
            height: 5,
        };

        let mut crossing = Diagram::new();
        crossing.add(Shape::Line {
            at: Pos { x: 0, y: 2 },
            len: 5,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });
        crossing.add(Shape::Line {
            at: Pos { x: 2, y: 0 },
            len: 5,
            orientation: Orientation::Vertical,
            stroke: light(),
        });
        let mut crossing_buffer = Buffer::new(origin, size);
        crossing.draw(&mut crossing_buffer);
        assert_eq!(
            render(&crossing_buffer, &GlyphCatalog::light(), origin, size),
            "  │  \n  │  \n──┼──\n  │  \n  │  \n"
        );

        let mut occluding = Diagram::new();
        occluding.add(Shape::Line {
            at: Pos { x: 2, y: 0 },
            len: 5,
            orientation: Orientation::Vertical,
            stroke: light(),
        });
        occluding.add(Shape::Box {
            at: Pos { x: 1, y: 1 },
            size: Size {
                width: 3,
                height: 3,
            },
            stroke: light(),
            fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
        });
        let mut occluding_buffer = Buffer::new(origin, size);
        occluding.draw(&mut occluding_buffer);
        assert_eq!(
            render(&occluding_buffer, &GlyphCatalog::light(), origin, size),
            "  │  \n ┌┴┐ \n │░│ \n └┬┘ \n  │  \n"
        );
    }

    /// TE-002: two partially overlapping opaque boxes, drawn before and after the back one moves
    /// forward, produce different buffers, and the second equals what the same two boxes added in
    /// the opposite order produce.
    #[test]
    fn moving_the_back_one_forward_matches_adding_them_in_the_opposite_order() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        let back = diagram.add(a);
        diagram.add(b);
        let mut before = Buffer::new(origin, size);
        diagram.draw(&mut before);

        diagram.forward(&back);
        let mut after = Buffer::new(origin, size);
        diagram.draw(&mut after);

        assert_ne!(cells(&before, origin, size), cells(&after, origin, size));

        let (a, b) = overlapping_boxes();
        let mut opposite = Diagram::new();
        opposite.add(b);
        opposite.add(a);
        let mut opposite_buffer = Buffer::new(origin, size);
        opposite.draw(&mut opposite_buffer);

        assert_eq!(
            cells(&after, origin, size),
            cells(&opposite_buffer, origin, size)
        );
    }

    /// TE-003: the same expected buffer comes from moving the front one backward instead, against
    /// the same two boxes.
    #[test]
    fn moving_the_front_one_backward_matches_moving_the_back_one_forward() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        diagram.add(a);
        let front = diagram.add(b);
        diagram.backward(&front);
        let mut buffer = Buffer::new(origin, size);
        diagram.draw(&mut buffer);

        let (a, b) = overlapping_boxes();
        let mut opposite = Diagram::new();
        opposite.add(b);
        opposite.add(a);
        let mut opposite_buffer = Buffer::new(origin, size);
        opposite.draw(&mut opposite_buffer);

        assert_eq!(
            cells(&buffer, origin, size),
            cells(&opposite_buffer, origin, size)
        );
    }

    /// TE-004: moving the front-most forward, and moving the back-most backward, each leave the
    /// drawn buffer unchanged.
    #[test]
    fn moving_the_front_most_forward_or_the_back_most_backward_changes_nothing() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        let back = diagram.add(a);
        let front = diagram.add(b);
        let mut before = Buffer::new(origin, size);
        diagram.draw(&mut before);

        diagram.forward(&front);
        let mut after_forward = Buffer::new(origin, size);
        diagram.draw(&mut after_forward);
        assert_eq!(
            cells(&before, origin, size),
            cells(&after_forward, origin, size)
        );

        diagram.backward(&back);
        let mut after_backward = Buffer::new(origin, size);
        diagram.draw(&mut after_backward);
        assert_eq!(
            cells(&before, origin, size),
            cells(&after_backward, origin, size)
        );
    }

    /// TE-004, edge case: a diagram holding one shape is unchanged by either move, since that
    /// shape is both front-most and back-most.
    #[test]
    fn a_diagram_holding_one_shape_is_unchanged_by_either_move() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 4,
            height: 3,
        };
        let mut diagram = Diagram::new();
        let only = diagram.add(Shape::Box {
            at: Pos { x: 0, y: 0 },
            size: Size {
                width: 4,
                height: 3,
            },
            stroke: light(),
            fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
        });
        let mut before = Buffer::new(origin, size);
        diagram.draw(&mut before);

        diagram.forward(&only);
        diagram.backward(&only);
        let mut after = Buffer::new(origin, size);
        diagram.draw(&mut after);

        assert_eq!(cells(&before, origin, size), cells(&after, origin, size));
    }

    /// TE-005, edge case: an identity kept from another diagram changes nothing through either
    /// method, with no panic.
    #[test]
    fn an_identity_from_another_diagram_changes_nothing_and_does_not_panic() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        diagram.add(a);
        diagram.add(b);
        let mut before = Buffer::new(origin, size);
        diagram.draw(&mut before);

        let mut other = Diagram::new();
        let foreign = other.add(Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });

        diagram.forward(&foreign);
        diagram.backward(&foreign);
        let mut after = Buffer::new(origin, size);
        diagram.draw(&mut after);

        assert_eq!(cells(&before, origin, size), cells(&after, origin, size));
    }

    /// TE-005, edge case: an empty diagram is unchanged by either method, with no panic.
    #[test]
    fn an_empty_diagram_is_unchanged_by_either_move() {
        let mut other = Diagram::new();
        let foreign = other.add(Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });

        let mut diagram = Diagram::new();
        diagram.forward(&foreign);
        diagram.backward(&foreign);

        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 3,
            height: 3,
        };
        let mut buffer = Buffer::new(origin, size);
        diagram.draw(&mut buffer);

        assert_eq!(
            cells(&buffer, origin, size),
            vec![None; (size.width * size.height) as usize]
        );
    }

    /// TE-006: a shape moved forward and then backward by the same identity draws exactly what it
    /// drew at the start.
    #[test]
    fn moving_a_shape_forward_then_backward_restores_the_original_drawing() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        let back = diagram.add(a);
        diagram.add(b);
        let mut before = Buffer::new(origin, size);
        diagram.draw(&mut before);

        diagram.forward(&back);
        diagram.backward(&back);
        let mut after = Buffer::new(origin, size);
        diagram.draw(&mut after);

        assert_eq!(cells(&before, origin, size), cells(&after, origin, size));
    }

    /// Edge case: two unfilled boxes with the same stroke whose shared cells every side leaves
    /// `Unset` — an inner box entirely inside an outer box's interior, so their border cells never
    /// coincide — draw identically before and after a reorder.
    #[test]
    fn two_unfilled_boxes_with_no_shared_cell_draw_identically_regardless_of_order() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 5,
        };
        let outer = || Shape::Box {
            at: Pos { x: 0, y: 0 },
            size: Size {
                width: 6,
                height: 5,
            },
            stroke: light(),
            fill: None,
        };
        let inner = || Shape::Box {
            at: Pos { x: 2, y: 2 },
            size: Size {
                width: 2,
                height: 2,
            },
            stroke: light(),
            fill: None,
        };

        let mut outer_then_inner = Diagram::new();
        outer_then_inner.add(outer());
        outer_then_inner.add(inner());
        let mut a = Buffer::new(origin, size);
        outer_then_inner.draw(&mut a);

        let mut inner_then_outer = Diagram::new();
        inner_then_outer.add(inner());
        inner_then_outer.add(outer());
        let mut b = Buffer::new(origin, size);
        inner_then_outer.draw(&mut b);

        assert_eq!(cells(&a, origin, size), cells(&b, origin, size));
    }

    // ------------------------------------------------------ a figure displaced by a delta

    /// Draws `shapes` into a fresh window, in the order given, so that a figure is observed the
    /// only way this crate lets it be observed. Both sides of every comparison below arrive
    /// through here: the figure displaced, and the same figure added where it landed.
    fn drawn(shapes: Vec<Shape>, origin: Pos, size: Size) -> Buffer {
        let mut diagram = Diagram::new();
        for shape in shapes {
            diagram.add(shape);
        }
        draw_of(&diagram, origin, size)
    }

    /// Draws a diagram the caller already holds, for a claim about what a change to it did.
    fn draw_of(diagram: &Diagram, origin: Pos, size: Size) -> Buffer {
        let mut buffer = Buffer::new(origin, size);
        diagram.draw(&mut buffer);
        buffer
    }

    /// The positions where two buffers of one window differ, so that a claim about which cells a
    /// change reached can be made by coordinates rather than by reading two pictures side by side.
    fn differing(before: &Buffer, after: &Buffer, origin: Pos, size: Size) -> Vec<Pos> {
        (0..size.height)
            .flat_map(|dy| (0..size.width).map(move |dx| (dx, dy)))
            .map(|(dx, dy)| Pos {
                x: origin.x + i32::try_from(dx).expect("width fits i32"),
                y: origin.y + i32::try_from(dy).expect("height fits i32"),
            })
            .filter(|at| before.cell(*at) != after.cell(*at))
            .collect()
    }

    /// Three filled boxes that all overlap one another, so which of them is front-most decides the
    /// cells they share and a change of order changes the picture. The first is the back-most and
    /// the last the front-most, and the second overlaps both.
    fn three_overlapping_boxes() -> (Shape, Shape, Shape) {
        let filled_box = |at: Pos, fill: &str| Shape::Box {
            at,
            size: Size {
                width: 4,
                height: 3,
            },
            stroke: light(),
            fill: Some(Glyph::new(fill).expect("one glyph")),
        };
        (
            filled_box(Pos { x: 0, y: 0 }, "░"),
            filled_box(Pos { x: 2, y: 1 }, "▓"),
            filled_box(Pos { x: 0, y: 1 }, "▒"),
        )
    }

    /// An identity no diagram in these tests holds, and the one the specification's cases mean by
    /// an identity from another diagram.
    ///
    /// It is the **third** identity another diagram issued rather than its first, because
    /// `ShapeId` is a string: an identity from elsewhere matches nothing here only because its
    /// number differs, and a diagram that issued one shape issues `#1`, which is exactly the
    /// identity a diagram holding two shapes has already used.
    fn a_foreign_identity() -> ShapeId {
        let a_line = || Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        };
        let mut other = Diagram::new();
        other.add(a_line());
        other.add(a_line());
        other.add(a_line())
    }

    /// User Story 1, spec's B3.1 scenario, SC-004: a box displaced two cells right draws exactly
    /// what the same box added at the displaced position draws.
    ///
    /// The expected picture is built by adding the box where it landed rather than pinned as text,
    /// so what is asserted is where a displacement puts a figure and not how a box draws. A
    /// displacement that quietly did nothing would draw the box where it already stood, and the two
    /// pictures would differ.
    #[test]
    fn a_displaced_box_draws_where_the_same_box_at_that_position_would_draw() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 9,
            height: 3,
        };
        let box_at = |x: i32| Shape::Box {
            at: Pos { x, y: 0 },
            size: Size {
                width: 4,
                height: 3,
            },
            stroke: light(),
            fill: None,
        };

        let moved = box_at(1).displaced_by(Delta { dx: 2, dy: 0 });

        assert_eq!(
            cells(&drawn(vec![moved], origin, size), origin, size),
            cells(&drawn(vec![box_at(3)], origin, size), origin, size)
        );
    }

    /// User Story 1, spec's B3.2 scenario, SC-004: a connector displaced two cells down draws
    /// exactly what the same connector added with **both** endpoints at `y + 2` draws.
    ///
    /// Both endpoints is the whole claim, and it is why the expected picture is built from the two
    /// positions rather than pinned as text. A displacement that moved one endpoint draws a
    /// connector between two rows, and one that moved neither is the silent no-op the previous
    /// system shipped along with a `// TODO: implement it`. Either passes a comparison against a
    /// picture of a connector that never moved, so this is the one neither passes.
    #[test]
    fn a_displaced_connector_draws_with_both_endpoints_moved() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 7,
            height: 5,
        };
        let connector = |from: Pos, to: Pos| Shape::Connector {
            from: Endpoint {
                at: from.into(),
                leaving: Direction::Right,
                terminal: Terminal::Glyph {
                    glyph: Glyph::new("◄").expect("one glyph"),
                },
            },
            to: Endpoint {
                at: to.into(),
                leaving: Direction::Left,
                terminal: Terminal::Glyph {
                    glyph: Glyph::new("►").expect("one glyph"),
                },
            },
            stroke: light(),
        };

        let moved =
            connector(Pos { x: 1, y: 1 }, Pos { x: 5, y: 1 }).displaced_by(Delta { dx: 0, dy: 2 });

        assert_eq!(
            cells(&drawn(vec![moved], origin, size), origin, size),
            cells(
                &drawn(
                    vec![connector(Pos { x: 1, y: 3 }, Pos { x: 5, y: 3 })],
                    origin,
                    size
                ),
                origin,
                size
            )
        );
    }

    /// User Story 1, spec's B3.3 scenario: displacing a figure a diagram holds changes no cell of
    /// it. A displacement builds a value; putting that value back under an identity is what changes
    /// anything. The second half of the rule is T026, which needs `replace` to exist.
    ///
    /// The `assert_ne!` is what keeps the test honest: without it a `displaced_by` that moved
    /// nothing would satisfy "changed no cell" by doing exactly that, and the rule would go
    /// unchecked.
    #[test]
    fn displacing_a_figure_the_diagram_holds_changes_no_cell_of_it() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        diagram.add(a.clone());
        diagram.add(b);
        let mut before = Buffer::new(origin, size);
        diagram.draw(&mut before);

        let displaced = a.displaced_by(Delta { dx: 1, dy: 2 });
        let mut after = Buffer::new(origin, size);
        diagram.draw(&mut after);

        assert_eq!(cells(&before, origin, size), cells(&after, origin, size));
        assert_ne!(displaced, a);
    }

    // ------------------------------------------- reading a figure back, and the two changes

    /// User Story 2, spec's B4.1 scenario: `get` on the identity `add` handed back returns a figure
    /// equal by value to the one added.
    ///
    /// Compared by value rather than by picture, because this is the only rule in the slice no
    /// picture can show. The widened derives are what make it sayable at all, and what comes back
    /// is the bare figure: the identity and the place in the order are the diagram's, held beside
    /// the figure rather than inside it.
    #[test]
    fn get_returns_the_figure_the_addition_named() {
        let (a, _b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        let id = diagram.add(a.clone());

        assert_eq!(diagram.get(&id), Some(&a));
    }

    /// User Story 2, spec's B4.2 scenario, SC-003: `get` on an identity this diagram does not hold
    /// gives nothing, and the picture it draws is the one it drew before.
    ///
    /// The identity is one another diagram issued, which is the case the specification means.
    #[test]
    fn get_on_an_identity_from_another_diagram_gives_nothing_and_changes_nothing() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        diagram.add(a);
        diagram.add(b);
        let before = draw_of(&diagram, origin, size);

        assert_eq!(diagram.get(&a_foreign_identity()), None);
        assert_eq!(
            cells(&before, origin, size),
            cells(&draw_of(&diagram, origin, size), origin, size)
        );
    }

    /// User Story 3, spec's B1.1 scenario, SC-001: a diagram of several figures, drawn before and
    /// after one is taken out, produces different buffers, and the figures that stayed draw exactly
    /// what they drew on their own.
    ///
    /// Three overlapping boxes rather than a row, and the one taken out is the first of the three
    /// rather than a figure in the middle. That is what makes the test say something a swap with
    /// the last entry could not pass: closing the gap leaves the survivors in the order they were,
    /// so the one that was in front is still in front, and swapping the removed entry with the
    /// back-most would hand the diagram the other two pictures instead.
    #[test]
    fn taking_a_shape_out_changes_the_picture_and_leaves_the_rest_drawing_what_they_drew() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (first, second, third) = three_overlapping_boxes();

        let mut diagram = Diagram::new();
        let taken_out = diagram.add(first);
        diagram.add(second.clone());
        diagram.add(third.clone());
        let before = draw_of(&diagram, origin, size);

        diagram.remove(&taken_out);
        let after = draw_of(&diagram, origin, size);

        assert_ne!(cells(&before, origin, size), cells(&after, origin, size));
        assert_eq!(
            cells(&after, origin, size),
            cells(&drawn(vec![second, third], origin, size), origin, size)
        );
    }

    /// User Story 3, spec's B1.2 scenario, SC-003: taking out an identity this diagram does not
    /// hold leaves the buffer exactly as it was, with no error, no report and no panic. The
    /// identity is one another diagram issued, which is the case worth running: a well-formed
    /// value that matches nothing here.
    #[test]
    fn taking_out_an_identity_from_another_diagram_changes_nothing_and_does_not_panic() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        diagram.add(a);
        diagram.add(b);
        let before = draw_of(&diagram, origin, size);

        diagram.remove(&a_foreign_identity());

        assert_eq!(
            cells(&before, origin, size),
            cells(&draw_of(&diagram, origin, size), origin, size)
        );
    }

    /// User Story 3, spec's B1.3 scenario, SC-005: take `#1` out, add a figure, and the identity
    /// handed back is `#3` rather than `#1`.
    ///
    /// Asserted by the identity's own text rather than by a picture, and it needs no code beyond
    /// the absence of a decrement, because `add` already increments before use.
    #[test]
    fn an_identity_is_never_handed_out_again_after_a_removal() {
        let a_line = || Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        };

        let mut diagram = Diagram::new();
        let first = diagram.add(a_line());
        diagram.add(a_line());
        assert_eq!(first.to_string(), "#1");

        diagram.remove(&first);
        let after_the_removal = diagram.add(a_line());

        assert_eq!(after_the_removal.to_string(), "#3");
    }

    /// Edge case: the last shape taken out leaves an empty diagram, and drawing an empty diagram
    /// leaves the buffer as it was. The rule `an_empty_diagram_leaves_its_buffer_untouched` already
    /// pins, reached here through a removal rather than through a diagram never given anything.
    #[test]
    fn taking_out_the_last_shape_leaves_an_empty_diagram() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, _b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        let only = diagram.add(a);

        diagram.remove(&only);

        assert_eq!(
            cells(&draw_of(&diagram, origin, size), origin, size),
            vec![None; (size.width * size.height) as usize]
        );
    }

    /// User Story 4, spec's B2.1 scenario, SC-002: a box put back as a wider box draws exactly what
    /// that wider box added on its own produces.
    ///
    /// Pinned against the wider box's own picture rather than against the box it replaced, which is
    /// what makes the claim about the figure handed in and not about a difference between two.
    #[test]
    fn a_box_put_back_as_a_wider_box_draws_that_wider_box() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 9,
            height: 3,
        };
        let box_of = |width: u32| Shape::Box {
            at: Pos { x: 1, y: 0 },
            size: Size { width, height: 3 },
            stroke: light(),
            fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
        };

        let mut diagram = Diagram::new();
        let id = diagram.add(box_of(4));
        diagram.replace(&id, box_of(7));

        assert_eq!(
            cells(&draw_of(&diagram, origin, size), origin, size),
            cells(&drawn(vec![box_of(7)], origin, size), origin, size)
        );
    }

    /// User Story 4, spec's B2.2 scenario, SC-002: a box put back as a line draws the line, kind
    /// included, and nothing of the previous figure survives.
    ///
    /// The pair the specification draws by hand and calls hypothetical, each side pinned against
    /// the figure handed in rather than against the other, which is what turns "nothing of the
    /// previous figure survives" into a checked claim rather than a comparison of two pictures.
    #[test]
    fn a_box_put_back_as_a_line_draws_the_line() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 4,
            height: 3,
        };
        let the_box = || Shape::Box {
            at: Pos { x: 0, y: 0 },
            size: Size {
                width: 4,
                height: 3,
            },
            stroke: light(),
            fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
        };
        let the_line = || Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 4,
            orientation: Orientation::Horizontal,
            stroke: light(),
        };

        let mut diagram = Diagram::new();
        let id = diagram.add(the_box());
        diagram.replace(&id, the_line());

        assert_eq!(
            cells(&draw_of(&diagram, origin, size), origin, size),
            cells(&drawn(vec![the_line()], origin, size), origin, size)
        );
    }

    /// User Story 4, spec's B2.3 scenario: a figure overlapping another, put back under its own
    /// identity unchanged, resolves the overlap as it did.
    ///
    /// This is what shows a replacement is not a reorder, and the second assertion says so
    /// directly: it holds up the order a remove-and-add would have produced as the picture that
    /// replacement must **not** draw. Two figures would not have been enough, since removing the
    /// front-most of two and adding it back leaves the order it was.
    #[test]
    fn a_figure_put_back_unchanged_resolves_its_overlap_as_it_did() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b, c) = three_overlapping_boxes();
        let mut diagram = Diagram::new();
        diagram.add(a.clone());
        let middle = diagram.add(b.clone());
        diagram.add(c.clone());
        let before = draw_of(&diagram, origin, size);

        diagram.replace(&middle, b.clone());
        let after = draw_of(&diagram, origin, size);

        assert_eq!(cells(&before, origin, size), cells(&after, origin, size));
        assert_ne!(
            cells(&after, origin, size),
            cells(&drawn(vec![a, c, b], origin, size), origin, size)
        );
    }

    /// User Story 4, spec's B2.4 scenario, SC-003: a shape put under an identity this diagram does
    /// not hold leaves the picture alone **and adds nothing**.
    ///
    /// The figure handed in is placed where it would be plainly visible, so a `replace` that fell
    /// back to removing the old entry and adding the new one would fail on the picture rather than
    /// on a count. The identity assertion is the other half: `#1` still names the figure it always
    /// named, so there is no way to name a shape into existence.
    #[test]
    fn a_shape_put_under_a_foreign_identity_is_neither_drawn_nor_added() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        diagram.add(a.clone());
        diagram.add(b);
        let before = draw_of(&diagram, origin, size);

        diagram.replace(
            &a_foreign_identity(),
            Shape::Box {
                at: Pos { x: 1, y: 1 },
                size: Size {
                    width: 3,
                    height: 3,
                },
                stroke: light(),
                fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
            },
        );
        let after = draw_of(&diagram, origin, size);

        assert_eq!(cells(&before, origin, size), cells(&after, origin, size));
        assert_eq!(diagram.get(&ShapeId::new("#1")), Some(&a));
    }

    /// User Story 1, spec's B3.3 scenario, second half: draw, displace, `replace`, and the picture
    /// is the one the same three figures draw with the middle one standing where the displacement
    /// put it.
    ///
    /// It lands beside the replacement rather than beside the displacement because it is the half
    /// that needs `replace` to exist. The reach is then pinned by coordinates: the cells the
    /// figure held before and the cells it holds now, and not one more. A change reaching a cell
    /// of either box, which is what a move implemented as a removal and an addition would do, is
    /// outside that set.
    #[test]
    fn putting_a_displaced_figure_back_reaches_only_the_cells_that_figure_holds() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 11,
            height: 3,
        };
        let filled_box = |x: i32, fill: &str| Shape::Box {
            at: Pos { x, y: 0 },
            size: Size {
                width: 3,
                height: 3,
            },
            stroke: light(),
            fill: Some(Glyph::new(fill).expect("one glyph")),
        };
        let the_line = |x: i32| Shape::Line {
            at: Pos { x, y: 1 },
            len: 5,
            orientation: Orientation::Horizontal,
            stroke: light(),
        };

        let mut diagram = Diagram::new();
        diagram.add(filled_box(0, "░"));
        let middle = diagram.add(the_line(3));
        diagram.add(filled_box(8, "▓"));
        let before = draw_of(&diagram, origin, size);

        let moved = the_line(3).displaced_by(Delta { dx: 2, dy: 0 });
        diagram.replace(&middle, moved.clone());
        let after = draw_of(&diagram, origin, size);

        assert_eq!(
            cells(&after, origin, size),
            cells(
                &drawn(
                    vec![filled_box(0, "░"), moved, filled_box(8, "▓")],
                    origin,
                    size
                ),
                origin,
                size
            )
        );

        let held_by_the_line = |at: Pos| at.y == 1 && (3..=9).contains(&at.x);
        let reached = differing(&before, &after, origin, size);
        assert!(
            !reached.is_empty(),
            "the displacement reached nothing at all"
        );
        assert!(
            reached.iter().all(|at| held_by_the_line(*at)),
            "the change reached outside the displaced figure: {reached:?}"
        );
    }

    // ----------------------------------------- an endpoint that hangs from another figure's side

    /// The box every case below hangs an endpoint from: four by three at the origin, so its right
    /// side center is `{3, 1}` — the point the shipped demonstration's connector already holds, and
    /// the one the model shows an endpoint attached at.
    const THE_SIDE_CENTRE: Pos = Pos { x: 3, y: 1 };

    fn the_box() -> Shape {
        Shape::Box {
            at: Pos { x: 0, y: 0 },
            size: Size {
                width: 4,
                height: 3,
            },
            stroke: light(),
            fill: None,
        }
    }

    /// A connector with both ends as arms and the given positions, so a picture's difference is the
    /// route and the two cells it starts and ends on, and nothing else about how a terminal draws.
    ///
    /// The directions are the caller's rather than the anchor's (§6 _Attachment_), so a case that
    /// puts the reference in the other slot has to name them the other way round rather than reuse
    /// these: a connector leaving rightward from its far end takes a different route, and one that
    /// did is testing the direction rather than the anchor.
    fn arm_connector(from: Position, to: Position) -> Shape {
        connector_leaving(from, Direction::Right, to, Direction::Left)
    }

    fn connector_leaving(
        from: Position,
        leaving: Direction,
        to: Position,
        arriving: Direction,
    ) -> Shape {
        Shape::Connector {
            from: Endpoint {
                at: from,
                leaving,
                terminal: Terminal::Arm,
            },
            to: Endpoint {
                at: to,
                leaving: arriving,
                terminal: Terminal::Arm,
            },
            stroke: light(),
        }
    }

    /// A second box that has nothing to do with either end, placed clear of everything else so that
    /// "this other figure drew exactly what it drew" is readable.
    fn the_unrelated_box() -> Shape {
        Shape::Box {
            at: Pos { x: 9, y: 0 },
            size: Size {
                width: 3,
                height: 3,
            },
            stroke: light(),
            fill: Some(Glyph::new("░").expect("one glyph")),
        }
    }

    /// The window the cases below are drawn in.
    fn the_window() -> (Pos, Size) {
        (
            Pos { x: 0, y: 0 },
            Size {
                width: 13,
                height: 4,
            },
        )
    }

    /// User Story 2, spec's B2.1, SC-001: a connector whose `from` hangs from a box's right side
    /// draws exactly what the same connector with `from` at that point draws.
    ///
    /// Each side is pinned against the point rather than against the other, which is what keeps a
    /// reference resolving to the wrong place from passing on a pair that are wrong together. So the
    /// coordinates are asserted first and the picture second: `resolve` has to be `{3, 1}` on its
    /// own account, and only then do the two drawings have to agree.
    #[test]
    fn a_hanging_endpoint_draws_what_the_point_it_resolves_to_draws() {
        let (origin, size) = the_window();

        let mut diagram = Diagram::new();
        let box_id = diagram.add(the_box());
        let hanging = arm_connector(
            Position::Reference(Reference {
                id: box_id.clone(),
                anchor: Anchor::Right,
            }),
            Pos { x: 8, y: 1 }.into(),
        );
        diagram.add(hanging.clone());

        // Pinned by coordinates first: a reference that resolved anywhere else fails here.
        let Shape::Connector { from, .. } = &hanging else {
            unreachable!("the figure above is a connector")
        };
        assert_eq!(from.at.resolve(&diagram), Some(THE_SIDE_CENTRE));

        let mut absolute = Diagram::new();
        absolute.add(the_box());
        absolute.add(arm_connector(
            THE_SIDE_CENTRE.into(),
            Pos { x: 8, y: 1 }.into(),
        ));

        assert_eq!(
            cells(&draw_of(&diagram, origin, size), origin, size),
            cells(&draw_of(&absolute, origin, size), origin, size)
        );
    }

    /// User Story 2, spec's B2.2, SC-002 and SC-005: displacing the box four cells right takes the
    /// hanging end with it, re-routes the connector to the end that did not move, and touches
    /// nothing else.
    ///
    /// The expected picture is built from the two positions rather than pinned as text, so what is
    /// claimed is where a displacement puts a figure and not how a connector draws. The reach is
    /// then pinned by coordinates: no column past the far endpoint moved, and that endpoint's own
    /// cell is byte-identical before and after. A resolution cached when the diagram was built
    /// rather than asked when it is drawn passes the first comparison and fails both of these.
    #[test]
    fn a_displaced_box_takes_the_endpoint_hanging_from_it_along() {
        let (origin, size) = the_window();
        let the_far_end = Pos { x: 11, y: 1 };

        let mut diagram = Diagram::new();
        let box_id = diagram.add(the_box());
        diagram.add(arm_connector(
            Position::Reference(Reference {
                id: box_id.clone(),
                anchor: Anchor::Right,
            }),
            the_far_end.into(),
        ));
        let before = draw_of(&diagram, origin, size);

        let moved = the_box().displaced_by(Delta { dx: 4, dy: 0 });
        diagram.replace(&box_id, moved);
        let after = draw_of(&diagram, origin, size);

        // The same two figures with the box where it landed and the endpoint at the point the
        // reference now resolves to: `{7, 1}`, four cells right of where it resolved before.
        let mut expected = Diagram::new();
        expected.add(Shape::Box {
            at: Pos { x: 4, y: 0 },
            size: Size {
                width: 4,
                height: 3,
            },
            stroke: light(),
            fill: None,
        });
        expected.add(arm_connector(Pos { x: 7, y: 1 }.into(), the_far_end.into()));

        assert_eq!(
            cells(&after, origin, size),
            cells(&draw_of(&expected, origin, size), origin, size)
        );

        let reached = differing(&before, &after, origin, size);
        assert!(
            !reached.is_empty(),
            "the displacement reached nothing at all"
        );
        assert!(
            reached.iter().all(|at| at.x <= the_far_end.x),
            "the change reached past the endpoint that did not move: {reached:?}"
        );
        assert_eq!(
            before.cell(the_far_end),
            after.cell(the_far_end),
            "the endpoint that did not move was drawn differently"
        );
    }

    /// User Story 2, spec's B2.3: a connector with one endpoint absolute and one hanging, each
    /// placed by its own rule.
    ///
    /// Both orders, because the two positions are the same field with different rules and a match
    /// written to suit one of them is the failure this case is for. Nothing here is pinned against
    /// the other arrangement: each is pinned against the same connector with both points absolute.
    #[test]
    fn a_connector_places_each_of_its_ends_by_its_own_rule() {
        let (origin, size) = the_window();
        // A box whose **bottom** side center is `{7, 2}`, so the two ends of the route below are
        // `{0, 2}` and `{7, 2}` and neither is the other.
        let the_held_box = || Shape::Box {
            at: Pos { x: 6, y: 0 },
            size: Size {
                width: 4,
                height: 3,
            },
            stroke: light(),
            fill: None,
        };
        let the_far_end = Pos { x: 0, y: 2 };
        let the_hanging_end = Pos { x: 7, y: 2 };

        // Each case is pinned against the same route with both ends named as points, and never
        // against the other case: a connector with its reference in the other slot leaves and
        // arrives the other way round, so the two are different routes and saying so is the point.
        let expected = |origin: Pos, size: Size| {
            let mut diagram = Diagram::new();
            diagram.add(the_held_box());
            diagram.add(arm_connector(the_far_end.into(), the_hanging_end.into()));
            cells(&draw_of(&diagram, origin, size), origin, size)
        };
        let expected_reversed = |origin: Pos, size: Size| {
            let mut diagram = Diagram::new();
            diagram.add(the_held_box());
            diagram.add(arm_connector(the_hanging_end.into(), the_far_end.into()));
            cells(&draw_of(&diagram, origin, size), origin, size)
        };

        let mut hanging_to = Diagram::new();
        let box_id = hanging_to.add(the_held_box());
        hanging_to.add(arm_connector(
            the_far_end.into(),
            Position::Reference(Reference {
                id: box_id,
                anchor: Anchor::Bottom,
            }),
        ));

        let mut hanging_from = Diagram::new();
        let box_id = hanging_from.add(the_held_box());
        hanging_from.add(arm_connector(
            Position::Reference(Reference {
                id: box_id,
                anchor: Anchor::Bottom,
            }),
            the_far_end.into(),
        ));

        assert_eq!(
            cells(&draw_of(&hanging_to, origin, size), origin, size),
            expected(origin, size)
        );
        assert_eq!(
            cells(&draw_of(&hanging_from, origin, size), origin, size),
            expected_reversed(origin, size)
        );
    }

    /// User Story 2, spec's B2.4, SC-003, and the three non-resolutions ADR-0041 enumerates: a
    /// reference to an identity this diagram does not hold, a reference to a kind that answers no
    /// anchor, and a connector with one endpoint that resolves and one that does not.
    ///
    /// Each case asserts two things together, and the second is what makes the first mean anything.
    /// The connector is **absent from the output**, and every other figure's cells are unchanged —
    /// which is what distinguishes "the connector is not drawn" from "the drawing stopped". The
    /// third case is the one a connector drawn partly would pass on the first half alone: half an
    /// arm is a route with no head, and only the whole-picture comparison rules it out.
    ///
    /// The three figures the endpoints do not touch are the same in every case, and the one the
    /// third case's unresolvable reference names is a connector, which answers no anchor at all.
    fn a_diagram_of_three_figures_and_maybe_a_fourth(under_test: Option<Shape>) -> Diagram {
        let mut diagram = Diagram::new();
        diagram.add(the_box());
        diagram.add(the_unrelated_box());
        // A connector, so that a reference naming it asks a kind that answers no anchor.
        diagram.add(arm_connector(
            Pos { x: 0, y: 3 }.into(),
            Pos { x: 12, y: 3 }.into(),
        ));
        if let Some(shape) = under_test {
            diagram.add(shape);
        }
        diagram
    }

    #[test]
    fn a_connector_with_an_endpoint_that_does_not_resolve_is_not_drawn_at_all() {
        let (origin, size) = the_window();
        let unresolvable = Position::Reference(Reference {
            id: a_foreign_identity(),
            anchor: Anchor::Right,
        });
        let answers_nothing = Position::Reference(Reference {
            id: crate::ShapeId::new("#3"),
            anchor: Anchor::Right,
        });
        let the_other_end: Position = Pos { x: 8, y: 1 }.into();

        let cases = [
            (
                "an identity nothing holds",
                unresolvable.clone(),
                the_other_end.clone(),
            ),
            (
                "a kind that answers no anchor",
                Pos { x: 5, y: 2 }.into(),
                answers_nothing,
            ),
            (
                "one end that resolves and one that does not",
                unresolvable,
                the_other_end,
            ),
        ];

        for (what, from, to) in cases {
            let with_it =
                a_diagram_of_three_figures_and_maybe_a_fourth(Some(arm_connector(from, to)));
            let without_it = a_diagram_of_three_figures_and_maybe_a_fourth(None);

            assert_eq!(
                cells(&draw_of(&with_it, origin, size), origin, size),
                cells(&draw_of(&without_it, origin, size), origin, size),
                "{what} drew something, or drew something else"
            );
        }
    }

    /// User Story 2, spec's B2.5: a reference to an identity nothing holds yet, and then a figure
    /// added under it — three kinds, because a kind answers anchors differently.
    ///
    /// The identity is spelled rather than read back, and **the connector is the first figure
    /// added** so that the figure under test is the one the counter names next. That is what makes
    /// the case reachable at all: a diagram offers no way to name a shape into existence, so a
    /// spelled identity can only ever be the one an `add` is about to issue. Nothing holds it at
    /// first and the hanging connector draws nothing; then a figure arrives and the same reference
    /// finds it.
    ///
    /// A `Box` answers, a `Line` answers as a flat box, and a `Connector` does not answer at all —
    /// which is the same picture as a reference to a shape that was never there.
    #[test]
    fn a_figure_added_under_a_spelled_identity_is_what_a_hanging_endpoint_finds() {
        let (origin, size) = the_window();
        let spelled = crate::ShapeId::new("#2");
        let the_far_end: Position = Pos { x: 11, y: 1 }.into();
        let the_filler = || arm_connector(Pos { x: 0, y: 0 }.into(), Pos { x: 1, y: 0 }.into());

        let hanging = |anchor| {
            arm_connector(
                Position::Reference(Reference {
                    id: spelled.clone(),
                    anchor,
                }),
                the_far_end.clone(),
            )
        };

        // Nothing holds `#2` yet, so the hanging connector draws nothing at all.
        let mut nothing_under_it = Diagram::new();
        nothing_under_it.add(hanging(Anchor::Right));
        nothing_under_it.add(the_filler());

        let mut just_the_filler = Diagram::new();
        just_the_filler.add(the_filler());
        assert_eq!(
            cells(&draw_of(&nothing_under_it, origin, size), origin, size),
            cells(&draw_of(&just_the_filler, origin, size), origin, size),
            "a reference to nothing drew something"
        );

        // A box takes `#2`, and the connector hangs from its right side.
        let mut with_a_box = Diagram::new();
        with_a_box.add(hanging(Anchor::Right));
        with_a_box.add(the_box());
        with_a_box.add(the_filler());

        let mut absolute_after_a_box = Diagram::new();
        absolute_after_a_box.add(the_filler());
        absolute_after_a_box.add(the_box());
        absolute_after_a_box.add(arm_connector(THE_SIDE_CENTRE.into(), the_far_end.clone()));
        assert_eq!(
            cells(&draw_of(&with_a_box, origin, size), origin, size),
            cells(&draw_of(&absolute_after_a_box, origin, size), origin, size),
            "a box under a spelled identity is not where a reference finds it"
        );

        // A line takes `#2` instead, and the connector lands on the line's own far end — read as a
        // box one cell thick, a five-cell line's right side center is its last cell.
        let the_line = || Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 5,
            orientation: Orientation::Horizontal,
            stroke: light(),
        };
        let mut with_a_line = Diagram::new();
        with_a_line.add(hanging(Anchor::Right));
        with_a_line.add(the_line());
        with_a_line.add(the_filler());

        let mut absolute_after_a_line = Diagram::new();
        absolute_after_a_line.add(the_filler());
        absolute_after_a_line.add(the_line());
        absolute_after_a_line.add(arm_connector(
            Pos { x: 4, y: 0 }.into(),
            the_far_end.clone(),
        ));
        assert_eq!(
            cells(&draw_of(&with_a_line, origin, size), origin, size),
            cells(&draw_of(&absolute_after_a_line, origin, size), origin, size),
            "a line under a spelled identity is not where a reference finds it"
        );

        // A connector takes `#2`, and the hanging connector stops drawing — the same answer as
        // before there was anything under the identity at all.
        let mut with_a_connector = Diagram::new();
        with_a_connector.add(hanging(Anchor::Right));
        with_a_connector.add(the_filler());

        assert_eq!(
            cells(&draw_of(&with_a_connector, origin, size), origin, size),
            cells(&draw_of(&just_the_filler, origin, size), origin, size),
            "a connector under a spelled identity still answered an anchor"
        );
    }

    /// User Story 2, and the claim the conversion's own test used to carry: a connector with a glyph
    /// terminal and a connector with an arm, each drawn through a diagram, produce the buffer the
    /// same core `Connector` drawn directly produces.
    ///
    /// A stronger pin than the conversion was, because it goes through the four lines that built it
    /// rather than naming them: a terminal or a direction dropped on the way would change the
    /// drawing, and the drawing is what is compared.
    #[test]
    fn a_connector_with_either_terminal_reaches_the_core_whole() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 8,
            height: 3,
        };
        let glyph = |text: &str| Terminal::Glyph {
            glyph: Glyph::new(text).expect("one glyph"),
        };

        for (from_terminal, to_terminal) in
            [(glyph("◄"), glyph("►")), (Terminal::Arm, Terminal::Arm)]
        {
            let endpoint = |at: Pos, leaving: Direction, terminal: Terminal| Endpoint {
                at: at.into(),
                leaving,
                terminal,
            };
            let from = endpoint(Pos { x: 0, y: 0 }, Direction::Down, from_terminal.clone());
            let to = endpoint(Pos { x: 7, y: 2 }, Direction::Up, to_terminal.clone());

            let mut diagram = Diagram::new();
            diagram.add(Shape::Connector {
                from: from.clone(),
                to: to.clone(),
                stroke: light(),
            });
            let mut actual = Buffer::new(origin, size);
            diagram.draw(&mut actual);

            let mut expected = Buffer::new(origin, size);
            Connector {
                from: monospace_core::Endpoint {
                    at: Pos { x: 0, y: 0 },
                    leaving: Direction::Down,
                    terminal: from_terminal,
                },
                to: monospace_core::Endpoint {
                    at: Pos { x: 7, y: 2 },
                    leaving: Direction::Up,
                    terminal: to_terminal,
                },
                stroke: light(),
            }
            .draw(&mut Layer::new(&mut expected, StampMode::Above));

            assert_eq!(cells(&actual, origin, size), cells(&expected, origin, size));
        }
    }

    /// User Story 3, spec's B3.1, SC-004: taking the referenced box out leaves the connector drawing
    /// nothing and leaves the figure that had nothing to do with either drawing exactly what it drew
    /// **on its own**.
    ///
    /// The second half is pinned against that box's own picture rather than against the first one,
    /// which is what makes the claim about the figures that stayed rather than a difference between
    /// two drawings. The reference is not rewritten, not reported and does not panic: taking the
    /// box out is 081's verb and this is what it now means.
    #[test]
    fn taking_the_referenced_figure_out_stops_the_connector_and_changes_nothing_else() {
        let (origin, size) = the_window();

        let mut diagram = Diagram::new();
        let box_id = diagram.add(the_box());
        diagram.add(arm_connector(
            Position::Reference(Reference {
                id: box_id.clone(),
                anchor: Anchor::Right,
            }),
            Pos { x: 8, y: 1 }.into(),
        ));
        diagram.add(the_unrelated_box());
        let before = draw_of(&diagram, origin, size);

        diagram.remove(&box_id);
        let after = draw_of(&diagram, origin, size);

        assert_ne!(cells(&before, origin, size), cells(&after, origin, size));
        assert_eq!(
            cells(&after, origin, size),
            cells(
                &drawn(vec![the_unrelated_box()], origin, size),
                origin,
                size
            )
        );
    }

    /// User Story 3, spec's B3.2, SC-004: a figure put back under the referenced identity makes the
    /// connector draw again, hanging from the **new** figure's side rather than where the old one
    /// stood.
    ///
    /// The case is put through `replace` rather than through `remove` followed by an addition, and
    /// the reason is the model's rather than a convenience: `remove` frees an identity permanently
    /// — `add` never hands one out twice, and there is no `add_under` — so a removal followed by an
    /// addition cannot put anything back under the removed one's identity, and the reference stays
    /// unresolved for good. What `replace` gives is the same resolution from the other side: the
    /// identity is found, the kind answers the anchor, and the connector is drawn from wherever the
    /// figure now stands. [#142](https://github.com/andresmoschini/monospace/issues/142) is where
    /// what a removal should do to a reference is answered.
    ///
    /// A **line** is what goes back, not a second box, so a kind change is covered by the same case:
    /// read as a box one cell thick, a five-cell line's right side center is its last cell, which is
    /// neither where the removed box answered nor the connector's own far end.
    #[test]
    fn a_figure_put_back_under_the_referenced_identity_draws_the_connector_again() {
        let (origin, size) = the_window();
        let the_far_end = Pos { x: 11, y: 1 };

        let mut diagram = Diagram::new();
        let identity = diagram.add(the_box());
        diagram.add(arm_connector(
            Position::Reference(Reference {
                id: identity.clone(),
                anchor: Anchor::Right,
            }),
            the_far_end.into(),
        ));
        let before = draw_of(&diagram, origin, size);

        let the_line = Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 5,
            orientation: Orientation::Horizontal,
            stroke: light(),
        };
        diagram.replace(&identity, the_line.clone());
        let after = draw_of(&diagram, origin, size);

        let mut expected = Diagram::new();
        expected.add(the_line);
        expected.add(arm_connector(Pos { x: 4, y: 0 }.into(), the_far_end.into()));

        assert_eq!(
            cells(&after, origin, size),
            cells(&draw_of(&expected, origin, size), origin, size)
        );
        assert_ne!(
            cells(&before, origin, size),
            cells(&after, origin, size),
            "the replacement did not reach the picture at all"
        );
    }

    /// User Story 4, spec's B4.2, SC-005: displacing a connector displaces the absolute endpoint and
    /// leaves the hanging one exactly where it was, and the route is drawn between the two.
    ///
    /// The expected picture is built from the two positions rather than pinned as text, so an
    /// implementation that moved both ends or neither fails. A displacement that did nothing at all
    /// passes on a connector that never hung from anything, which is why this case hangs.
    #[test]
    fn a_displaced_connector_moves_its_absolute_end_and_leaves_its_hanging_one() {
        let (origin, size) = the_window();

        let mut diagram = Diagram::new();
        let box_id = diagram.add(the_box());
        diagram.add(arm_connector(
            Pos { x: 0, y: 1 }.into(),
            Position::Reference(Reference {
                id: box_id.clone(),
                anchor: Anchor::Right,
            }),
        ));
        let before = draw_of(&diagram, origin, size);

        let id = crate::ShapeId::new("#2");
        let moved = diagram
            .get(&id)
            .expect("the connector is in the diagram")
            .displaced_by(Delta { dx: 0, dy: 2 });
        diagram.replace(&id, moved);
        let after = draw_of(&diagram, origin, size);

        let mut expected = Diagram::new();
        expected.add(the_box());
        expected.add(arm_connector(
            Pos { x: 0, y: 3 }.into(),
            THE_SIDE_CENTRE.into(),
        ));

        assert_eq!(
            cells(&after, origin, size),
            cells(&draw_of(&expected, origin, size), origin, size)
        );

        // The hanging end is untouched by coordinates as well as by picture: `{3, 1}` is the cell the
        // arm starts on in both drawings.
        assert_eq!(
            before.cell(THE_SIDE_CENTRE),
            after.cell(THE_SIDE_CENTRE),
            "the hanging end moved with the displacement"
        );
    }

    /// User Story 4, spec's B4.3: displacing a box or a line takes all four of its side centers with
    /// it, and a connector hanging from any of them goes with them.
    ///
    /// The other side of B4 from the rule above, and what makes a displacement a property of a
    /// position rather than of a figure. All four anchors rather than one, each with a destination
    /// of its own so that no two arms share a cell and no wrong answer can hide behind a right one:
    /// an implementation that moved three centers and left the fourth would draw three correct
    /// routes and one that goes nowhere.
    #[test]
    fn a_displaced_figure_takes_every_anchor_and_every_hanging_end_with_it() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 14,
            height: 6,
        };
        let by = Delta { dx: 2, dy: 0 };
        let the_anchors = [Anchor::Top, Anchor::Right, Anchor::Bottom, Anchor::Left];
        let the_destinations = [
            Pos { x: 12, y: 0 },
            Pos { x: 13, y: 1 },
            Pos { x: 13, y: 2 },
            Pos { x: 12, y: 5 },
        ];

        let a_box_at = |x: i32| Shape::Box {
            at: Pos { x, y: 0 },
            size: Size {
                width: 4,
                height: 3,
            },
            stroke: light(),
            fill: None,
        };
        let a_line_at = |x: i32| Shape::Line {
            at: Pos { x, y: 0 },
            len: 6,
            orientation: Orientation::Horizontal,
            stroke: light(),
        };

        for (what, figure_at) in [
            ("a box", &a_box_at as &dyn Fn(i32) -> Shape),
            ("a line", &a_line_at as &dyn Fn(i32) -> Shape),
        ] {
            let mut diagram = Diagram::new();
            let identity = diagram.add(figure_at(0));
            for (anchor, to) in the_anchors.into_iter().zip(the_destinations) {
                diagram.add(arm_connector(
                    Position::Reference(Reference {
                        id: identity.clone(),
                        anchor,
                    }),
                    to.into(),
                ));
            }
            let before = draw_of(&diagram, origin, size);

            let moved = figure_at(0).displaced_by(by);
            diagram.replace(&identity, moved.clone());
            let after = draw_of(&diagram, origin, size);

            // The same five figures with every anchor named as the point it resolved to before the
            // displacement, and again as the point it resolves to after.
            let mut expected_before = Diagram::new();
            expected_before.add(figure_at(0));
            for (anchor, to) in the_anchors.into_iter().zip(the_destinations) {
                expected_before.add(arm_connector(
                    figure_at(0)
                        .anchor(anchor)
                        .expect("a box and a line answer every anchor")
                        .into(),
                    to.into(),
                ));
            }
            assert_eq!(
                cells(&before, origin, size),
                cells(&draw_of(&expected_before, origin, size), origin, size),
                "{what} before"
            );

            let mut expected_after = Diagram::new();
            expected_after.add(moved.clone());
            for (anchor, to) in the_anchors.into_iter().zip(the_destinations) {
                expected_after.add(arm_connector(
                    moved
                        .anchor(anchor)
                        .expect("a box and a line answer every anchor")
                        .into(),
                    to.into(),
                ));
            }
            assert_eq!(
                cells(&after, origin, size),
                cells(&draw_of(&expected_after, origin, size), origin, size),
                "{what} after"
            );
        }
    }
}
