//! The diagram: an ordered set of shapes, drawable into a buffer the caller gives it. See
//! [`docs/diagram-model.md`](../../../docs/diagram-model.md) and
//! [ADR-0042](../../../docs/decisions/0042-draw-a-diagram-front-to-back-into-a-given-window.md).

use std::fmt;

use monospace_core::{Buffer, Layer, StampMode};

use crate::Shape;

/// A shape's identity, generated by the diagram that placed it and unique within it (FR-001,
/// FR-002). There is no way to build one directly: the only identities that exist are the ones a
/// diagram has handed out (FR-003).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ShapeId(String);

impl fmt::Display for ShapeId {
    /// Writes the identity as `#1`, `#2`, and so on.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

/// One entry of a diagram's order: a shape and the identity the diagram gave it.
struct Placed {
    id: ShapeId,
    shape: Shape,
}

/// A diagram: an ordered set of shapes, and nothing else — no buffer, no glyph catalog, no
/// rendered picture (FR-005).
#[derive(Default)]
pub struct Diagram {
    /// The order the shapes draw in. The **last** element is the front of the order (research.md
    /// Q2): it is drawn first and decides a shared cell before anything behind it.
    shapes: Vec<Placed>,
    /// The ordinal the next `add` numbers its identity with.
    next: u32,
}

impl Diagram {
    /// An empty diagram, holding no shapes.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Puts `shape` at the front of the order, in front of everything already there, and returns
    /// the identity the diagram gave it (FR-002, FR-006).
    pub fn add(&mut self, shape: Shape) -> ShapeId {
        self.next += 1;
        let id = ShapeId(format!("#{}", self.next));
        self.shapes.push(Placed {
            id: id.clone(),
            shape,
        });
        id
    }

    /// Moves the shape named by `id` one place toward the front of the order. Does nothing when
    /// `id` names no shape here, or when it is already the front-most (FR-007, FR-009, FR-010,
    /// FR-011).
    pub fn forward(&mut self, id: &ShapeId) {
        if let Some(index) = self.shapes.iter().position(|placed| &placed.id == id)
            && index + 1 < self.shapes.len()
        {
            self.shapes.swap(index, index + 1);
        }
    }

    /// Moves the shape named by `id` one place toward the back of the order. Does nothing when
    /// `id` names no shape here, or when it is already the back-most (FR-008, FR-009, FR-010,
    /// FR-011).
    pub fn backward(&mut self, id: &ShapeId) {
        if let Some(index) = self.shapes.iter().position(|placed| &placed.id == id)
            && index > 0
        {
            self.shapes.swap(index, index - 1);
        }
    }

    /// Draws every shape into `buffer`, front to back, stamping every cell with
    /// [`StampMode::Below`] (FR-010 to FR-012). Drawing changes nothing about this diagram
    /// (FR-015), so two drawings into equal windows produce equal buffers.
    pub fn draw(&self, buffer: &mut Buffer) {
        let mut layer = Layer::new(buffer, StampMode::Below);
        for placed in self.shapes.iter().rev() {
            placed.shape.draw(&mut layer);
        }
    }
}

#[cfg(test)]
mod tests {
    use monospace_core::{
        Arrow, BoxShape, Buffer, Cell, Direction, Glyph, GlyphCatalog, Layer, Line, Orientation,
        Pos, Shape as CoreShape, Size, StampMode, Stroke, render,
    };

    use super::Diagram;
    use crate::{Endpoint, Shape};

    fn light() -> Stroke {
        Stroke::from("light")
    }

    /// Collects every cell of `buffer` over the window `origin`/`size`, so two buffers can be
    /// compared by value even though `Buffer` derives no `PartialEq` (research.md Q7).
    fn cells(buffer: &Buffer, origin: Pos, size: Size) -> Vec<Option<Cell>> {
        (0..size.height)
            .flat_map(|dy| (0..size.width).map(move |dx| (dx, dy)))
            .map(|(dx, dy)| {
                let at = Pos {
                    x: origin.x + i32::try_from(dx).expect("width fits i32"),
                    y: origin.y + i32::try_from(dy).expect("height fits i32"),
                };
                buffer.cell(at).cloned()
            })
            .collect()
    }

    /// TE-003, scenarios 1 and 2: a diagram holding a box and a line, drawn twice into equal
    /// windows, produces equal buffers.
    #[test]
    fn drawing_the_same_diagram_twice_produces_equal_buffers() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 10,
            height: 5,
        };
        let mut diagram = Diagram::new();
        diagram.add(Shape::Box {
            at: Pos { x: 0, y: 0 },
            size: Size {
                width: 4,
                height: 3,
            },
            stroke: light(),
            fill: None,
        });
        diagram.add(Shape::Line {
            at: Pos { x: 0, y: 4 },
            len: 5,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });

        let mut first = Buffer::new(origin, size);
        diagram.draw(&mut first);
        let mut second = Buffer::new(origin, size);
        diagram.draw(&mut second);

        assert_eq!(cells(&first, origin, size), cells(&second, origin, size));
    }

    /// Scenario 3: an empty diagram leaves its buffer exactly as it was.
    #[test]
    fn an_empty_diagram_leaves_its_buffer_untouched() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 3,
            height: 3,
        };
        let mut buffer = Buffer::new(origin, size);
        Diagram::new().draw(&mut buffer);

        assert_eq!(
            cells(&buffer, origin, size),
            vec![None; (size.width * size.height) as usize]
        );
    }

    /// TE-002, scenario 4: a box partly outside the window draws what falls inside and nothing
    /// else, with no error.
    #[test]
    fn a_box_partly_outside_the_window_draws_only_what_falls_inside() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 3,
            height: 3,
        };
        let mut diagram = Diagram::new();
        diagram.add(Shape::Box {
            at: Pos { x: 1, y: 1 },
            size: Size {
                width: 4,
                height: 4,
            },
            stroke: light(),
            fill: None,
        });

        let mut buffer = Buffer::new(origin, size);
        diagram.draw(&mut buffer);

        assert!(buffer.cell(Pos { x: 1, y: 1 }).is_some());
        assert!(buffer.cell(Pos { x: 4, y: 4 }).is_none());
    }

    /// TE-005, scenario 5: a box drawn through a diagram matches the same `BoxShape` drawn
    /// directly.
    #[test]
    fn a_box_shape_matches_the_core_box_drawn_directly() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 3,
        };
        let mut diagram = Diagram::new();
        diagram.add(Shape::Box {
            at: origin,
            size,
            stroke: light(),
            fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
        });
        let mut actual = Buffer::new(origin, size);
        diagram.draw(&mut actual);

        let mut expected = Buffer::new(origin, size);
        BoxShape {
            at: origin,
            size,
            stroke: light(),
            fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
        }
        .draw(&mut Layer::new(&mut expected, StampMode::Above));

        assert_eq!(
            render(&actual, &GlyphCatalog::light(), origin, size),
            render(&expected, &GlyphCatalog::light(), origin, size)
        );
    }

    /// TE-005: a line drawn through a diagram matches the same `Line` drawn directly.
    #[test]
    fn a_line_shape_matches_the_core_line_drawn_directly() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 5,
            height: 1,
        };
        let mut diagram = Diagram::new();
        diagram.add(Shape::Line {
            at: origin,
            len: 5,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });
        let mut actual = Buffer::new(origin, size);
        diagram.draw(&mut actual);

        let mut expected = Buffer::new(origin, size);
        Line {
            at: origin,
            len: 5,
            orientation: Orientation::Horizontal,
            stroke: light(),
        }
        .draw(&mut Layer::new(&mut expected, StampMode::Above));

        assert_eq!(
            render(&actual, &GlyphCatalog::light(), origin, size),
            render(&expected, &GlyphCatalog::light(), origin, size)
        );
    }

    /// TE-005: an arrow drawn through a diagram matches the same `Arrow` drawn directly, both
    /// endpoints included.
    #[test]
    fn an_arrow_shape_matches_the_core_arrow_drawn_directly() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 5,
            height: 4,
        };
        let from = || Endpoint {
            at: Pos { x: 0, y: 0 },
            leaving: Direction::Down,
            head: Glyph::new("▼").expect("one glyph"),
        };
        let to = || Endpoint {
            at: Pos { x: 4, y: 3 },
            leaving: Direction::Left,
            head: Glyph::new("►").expect("one glyph"),
        };

        let mut diagram = Diagram::new();
        diagram.add(Shape::Arrow {
            from: from(),
            to: to(),
            stroke: light(),
        });
        let mut actual = Buffer::new(origin, size);
        diagram.draw(&mut actual);

        let mut expected = Buffer::new(origin, size);
        Arrow {
            from: from().into(),
            to: to().into(),
            stroke: light(),
        }
        .draw(&mut Layer::new(&mut expected, StampMode::Above));

        assert_eq!(
            render(&actual, &GlyphCatalog::light(), origin, size),
            render(&expected, &GlyphCatalog::light(), origin, size)
        );
    }

    /// TE-001: adding three shapes to one diagram yields three identities that differ from one
    /// another and read as `#1`, `#2`, `#3` in the order added.
    #[test]
    fn adding_three_shapes_yields_three_identities_in_order() {
        let mut diagram = Diagram::new();
        let first = diagram.add(Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });
        let second = diagram.add(Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });
        let third = diagram.add(Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });

        assert_eq!(first.to_string(), "#1");
        assert_eq!(second.to_string(), "#2");
        assert_eq!(third.to_string(), "#3");
        assert_ne!(first, second);
        assert_ne!(second, third);
        assert_ne!(first, third);
    }

    /// Spec.md US1 scenario 3: adding the same shape value twice yields two different identities.
    #[test]
    fn adding_the_same_shape_value_twice_yields_two_different_identities() {
        let shape = || Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        };
        let mut diagram = Diagram::new();
        let first = diagram.add(shape());
        let second = diagram.add(shape());

        assert_ne!(first, second);
    }

    /// Two overlapping boxes, each filled with its own glyph, so which one is front-most decides
    /// the shared cells rather than leaving both interior sides open (as two unfilled boxes with
    /// the same stroke do, order-independently).
    fn overlapping_boxes() -> (Shape, Shape) {
        (
            Shape::Box {
                at: Pos { x: 0, y: 0 },
                size: Size {
                    width: 4,
                    height: 3,
                },
                stroke: light(),
                fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
            },
            Shape::Box {
                at: Pos { x: 2, y: 1 },
                size: Size {
                    width: 4,
                    height: 3,
                },
                stroke: light(),
                fill: Some(Glyph::new("▓").expect("\"▓\" is one glyph")),
            },
        )
    }

    fn overlapping_core_boxes() -> (BoxShape, BoxShape) {
        (
            BoxShape {
                at: Pos { x: 0, y: 0 },
                size: Size {
                    width: 4,
                    height: 3,
                },
                stroke: light(),
                fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
            },
            BoxShape {
                at: Pos { x: 2, y: 1 },
                size: Size {
                    width: 4,
                    height: 3,
                },
                stroke: light(),
                fill: Some(Glyph::new("▓").expect("\"▓\" is one glyph")),
            },
        )
    }

    /// TE-001, scenario 1, SC-005: two overlapping boxes drawn front to back with `Below` produce
    /// the buffer that stamping the same two core shapes back to front with `Above` produces.
    #[test]
    fn front_to_back_with_below_equals_back_to_front_with_above() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        diagram.add(a);
        diagram.add(b);
        let mut actual = Buffer::new(origin, size);
        diagram.draw(&mut actual);

        let (core_a, core_b) = overlapping_core_boxes();
        let mut expected = Buffer::new(origin, size);
        core_a.draw(&mut Layer::new(&mut expected, StampMode::Above));
        core_b.draw(&mut Layer::new(&mut expected, StampMode::Above));

        assert_eq!(cells(&actual, origin, size), cells(&expected, origin, size));
    }

    /// TE-004, scenarios 2 and 5: the same two overlapping boxes in opposite orders produce
    /// different buffers, and in each the front-most shape's stroke decides the shared cells.
    #[test]
    fn opposite_orders_produce_different_buffers() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut a_then_b = Diagram::new();
        a_then_b.add(a);
        a_then_b.add(b);
        let mut a_then_b_buffer = Buffer::new(origin, size);
        a_then_b.draw(&mut a_then_b_buffer);

        let (a, b) = overlapping_boxes();
        let mut b_then_a = Diagram::new();
        b_then_a.add(b);
        b_then_a.add(a);
        let mut b_then_a_buffer = Buffer::new(origin, size);
        b_then_a.draw(&mut b_then_a_buffer);

        assert_ne!(
            cells(&a_then_b_buffer, origin, size),
            cells(&b_then_a_buffer, origin, size)
        );
    }

    /// Scenarios 3 and 4: a crossing is composition, not occlusion — a horizontal and a vertical
    /// line that cross make a junction glyph, and a filled box in front of a line hides it
    /// wherever the box's interior covers it, while the box's border still composes with the
    /// line into a junction where the two meet.
    #[test]
    fn a_crossing_composes_and_a_filled_box_occludes() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 5,
            height: 5,
        };

        let mut crossing = Diagram::new();
        crossing.add(Shape::Line {
            at: Pos { x: 0, y: 2 },
            len: 5,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });
        crossing.add(Shape::Line {
            at: Pos { x: 2, y: 0 },
            len: 5,
            orientation: Orientation::Vertical,
            stroke: light(),
        });
        let mut crossing_buffer = Buffer::new(origin, size);
        crossing.draw(&mut crossing_buffer);
        assert_eq!(
            render(&crossing_buffer, &GlyphCatalog::light(), origin, size),
            "  │  \n  │  \n──┼──\n  │  \n  │  \n"
        );

        let mut occluding = Diagram::new();
        occluding.add(Shape::Line {
            at: Pos { x: 2, y: 0 },
            len: 5,
            orientation: Orientation::Vertical,
            stroke: light(),
        });
        occluding.add(Shape::Box {
            at: Pos { x: 1, y: 1 },
            size: Size {
                width: 3,
                height: 3,
            },
            stroke: light(),
            fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
        });
        let mut occluding_buffer = Buffer::new(origin, size);
        occluding.draw(&mut occluding_buffer);
        assert_eq!(
            render(&occluding_buffer, &GlyphCatalog::light(), origin, size),
            "  │  \n ┌┴┐ \n │░│ \n └┬┘ \n  │  \n"
        );
    }

    /// TE-002: two partially overlapping opaque boxes, drawn before and after the back one moves
    /// forward, produce different buffers, and the second equals what the same two boxes added in
    /// the opposite order produce.
    #[test]
    fn moving_the_back_one_forward_matches_adding_them_in_the_opposite_order() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        let back = diagram.add(a);
        diagram.add(b);
        let mut before = Buffer::new(origin, size);
        diagram.draw(&mut before);

        diagram.forward(&back);
        let mut after = Buffer::new(origin, size);
        diagram.draw(&mut after);

        assert_ne!(cells(&before, origin, size), cells(&after, origin, size));

        let (a, b) = overlapping_boxes();
        let mut opposite = Diagram::new();
        opposite.add(b);
        opposite.add(a);
        let mut opposite_buffer = Buffer::new(origin, size);
        opposite.draw(&mut opposite_buffer);

        assert_eq!(
            cells(&after, origin, size),
            cells(&opposite_buffer, origin, size)
        );
    }

    /// TE-003: the same expected buffer comes from moving the front one backward instead, against
    /// the same two boxes.
    #[test]
    fn moving_the_front_one_backward_matches_moving_the_back_one_forward() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        diagram.add(a);
        let front = diagram.add(b);
        diagram.backward(&front);
        let mut buffer = Buffer::new(origin, size);
        diagram.draw(&mut buffer);

        let (a, b) = overlapping_boxes();
        let mut opposite = Diagram::new();
        opposite.add(b);
        opposite.add(a);
        let mut opposite_buffer = Buffer::new(origin, size);
        opposite.draw(&mut opposite_buffer);

        assert_eq!(
            cells(&buffer, origin, size),
            cells(&opposite_buffer, origin, size)
        );
    }

    /// TE-004: moving the front-most forward, and moving the back-most backward, each leave the
    /// drawn buffer unchanged.
    #[test]
    fn moving_the_front_most_forward_or_the_back_most_backward_changes_nothing() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        let back = diagram.add(a);
        let front = diagram.add(b);
        let mut before = Buffer::new(origin, size);
        diagram.draw(&mut before);

        diagram.forward(&front);
        let mut after_forward = Buffer::new(origin, size);
        diagram.draw(&mut after_forward);
        assert_eq!(
            cells(&before, origin, size),
            cells(&after_forward, origin, size)
        );

        diagram.backward(&back);
        let mut after_backward = Buffer::new(origin, size);
        diagram.draw(&mut after_backward);
        assert_eq!(
            cells(&before, origin, size),
            cells(&after_backward, origin, size)
        );
    }

    /// TE-004, edge case: a diagram holding one shape is unchanged by either move, since that
    /// shape is both front-most and back-most.
    #[test]
    fn a_diagram_holding_one_shape_is_unchanged_by_either_move() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 4,
            height: 3,
        };
        let mut diagram = Diagram::new();
        let only = diagram.add(Shape::Box {
            at: Pos { x: 0, y: 0 },
            size: Size {
                width: 4,
                height: 3,
            },
            stroke: light(),
            fill: Some(Glyph::new("░").expect("\"░\" is one glyph")),
        });
        let mut before = Buffer::new(origin, size);
        diagram.draw(&mut before);

        diagram.forward(&only);
        diagram.backward(&only);
        let mut after = Buffer::new(origin, size);
        diagram.draw(&mut after);

        assert_eq!(cells(&before, origin, size), cells(&after, origin, size));
    }

    /// TE-005, edge case: an identity kept from another diagram changes nothing through either
    /// method, with no panic.
    #[test]
    fn an_identity_from_another_diagram_changes_nothing_and_does_not_panic() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        diagram.add(a);
        diagram.add(b);
        let mut before = Buffer::new(origin, size);
        diagram.draw(&mut before);

        let mut other = Diagram::new();
        let foreign = other.add(Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });

        diagram.forward(&foreign);
        diagram.backward(&foreign);
        let mut after = Buffer::new(origin, size);
        diagram.draw(&mut after);

        assert_eq!(cells(&before, origin, size), cells(&after, origin, size));
    }

    /// TE-005, edge case: an empty diagram is unchanged by either method, with no panic.
    #[test]
    fn an_empty_diagram_is_unchanged_by_either_move() {
        let mut other = Diagram::new();
        let foreign = other.add(Shape::Line {
            at: Pos { x: 0, y: 0 },
            len: 1,
            orientation: Orientation::Horizontal,
            stroke: light(),
        });

        let mut diagram = Diagram::new();
        diagram.forward(&foreign);
        diagram.backward(&foreign);

        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 3,
            height: 3,
        };
        let mut buffer = Buffer::new(origin, size);
        diagram.draw(&mut buffer);

        assert_eq!(
            cells(&buffer, origin, size),
            vec![None; (size.width * size.height) as usize]
        );
    }

    /// TE-006: a shape moved forward and then backward by the same identity draws exactly what it
    /// drew at the start.
    #[test]
    fn moving_a_shape_forward_then_backward_restores_the_original_drawing() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 4,
        };
        let (a, b) = overlapping_boxes();
        let mut diagram = Diagram::new();
        let back = diagram.add(a);
        diagram.add(b);
        let mut before = Buffer::new(origin, size);
        diagram.draw(&mut before);

        diagram.forward(&back);
        diagram.backward(&back);
        let mut after = Buffer::new(origin, size);
        diagram.draw(&mut after);

        assert_eq!(cells(&before, origin, size), cells(&after, origin, size));
    }

    /// Edge case: two unfilled boxes with the same stroke whose shared cells every side leaves
    /// `Unset` — an inner box entirely inside an outer box's interior, so their border cells never
    /// coincide — draw identically before and after a reorder.
    #[test]
    fn two_unfilled_boxes_with_no_shared_cell_draw_identically_regardless_of_order() {
        let origin = Pos { x: 0, y: 0 };
        let size = Size {
            width: 6,
            height: 5,
        };
        let outer = || Shape::Box {
            at: Pos { x: 0, y: 0 },
            size: Size {
                width: 6,
                height: 5,
            },
            stroke: light(),
            fill: None,
        };
        let inner = || Shape::Box {
            at: Pos { x: 2, y: 2 },
            size: Size {
                width: 2,
                height: 2,
            },
            stroke: light(),
            fill: None,
        };

        let mut outer_then_inner = Diagram::new();
        outer_then_inner.add(outer());
        outer_then_inner.add(inner());
        let mut a = Buffer::new(origin, size);
        outer_then_inner.draw(&mut a);

        let mut inner_then_outer = Diagram::new();
        inner_then_outer.add(inner());
        inner_then_outer.add(outer());
        let mut b = Buffer::new(origin, size);
        inner_then_outer.draw(&mut b);

        assert_eq!(cells(&a, origin, size), cells(&b, origin, size));
    }
}
